// Auto-generated curated emoji dataset for the New-bundle icon picker.
// Curated subset (~500 entries), not the full Unicode set. Names are
// lowercase, human-readable (CLDR-style); keywords are hand-picked for
// search, richest on the Tools & tech group.

export interface EmojiEntry {
  char: string;
  name: string;
  keywords: string[];
}

export interface EmojiGroup {
  id: string;
  label: string;
  glyph: string;
  entries: EmojiEntry[];
}

const SUGGESTED_ENTRIES: EmojiEntry[] = [
  { char: "📦", name: "package", keywords: ["package", "box", "parcel", "ship", "release", "bundle"] },
  { char: "🔧", name: "wrench", keywords: ["wrench", "tool", "fix", "settings"] },
  { char: "⚡", name: "high voltage", keywords: ["lightning", "bolt", "electric", "power", "fast"] },
  { char: "🌿", name: "herb", keywords: ["herb", "leaf", "plant", "nature"] },
  { char: "🤖", name: "robot", keywords: ["robot", "bot", "agent", "ai", "automation"] },
  { char: "🛠️", name: "hammer and wrench", keywords: ["tools", "build", "repair", "construction"] },
  { char: "🧪", name: "test tube", keywords: ["test", "lab", "experiment", "science"] },
  { char: "📜", name: "scroll", keywords: ["scroll", "doc", "history", "log", "document"] },
  { char: "🔒", name: "locked", keywords: ["lock", "secure", "private", "closed"] },
  { char: "🌐", name: "globe with meridians", keywords: ["web", "globe", "internet", "world", "network"] },
  { char: "✨", name: "sparkles", keywords: ["sparkles", "new", "magic", "shiny"] },
  { char: "📁", name: "file folder", keywords: ["folder", "files", "directory", "index"] },
];

const TOOLS_ENTRIES: EmojiEntry[] = [
  { char: "🖥️", name: "desktop computer", keywords: ["computer", "monitor", "screen", "desktop"] },
  { char: "💻", name: "laptop", keywords: ["laptop", "computer", "code", "dev"] },
  { char: "⌨️", name: "keyboard", keywords: ["keyboard", "type", "input"] },
  { char: "🖱️", name: "computer mouse", keywords: ["mouse", "click", "pointer"] },
  { char: "🖨️", name: "printer", keywords: ["printer", "print"] },
  { char: "💾", name: "floppy disk", keywords: ["save", "disk", "storage", "floppy"] },
  { char: "💿", name: "optical disk", keywords: ["cd", "disk", "media"] },
  { char: "📀", name: "dvd", keywords: ["dvd", "disk", "media"] },
  { char: "🔌", name: "electric plug", keywords: ["plug", "power", "cable", "connect"] },
  { char: "🔋", name: "battery", keywords: ["battery", "power", "charge"] },
  { char: "📡", name: "satellite antenna", keywords: ["satellite", "antenna", "signal", "broadcast"] },
  { char: "🛰️", name: "satellite", keywords: ["satellite", "space", "orbit"] },
  { char: "📱", name: "mobile phone", keywords: ["phone", "mobile", "device"] },
  { char: "☎️", name: "telephone", keywords: ["phone", "call", "telephone"] },
  { char: "📞", name: "telephone receiver", keywords: ["phone", "call"] },
  { char: "📟", name: "pager", keywords: ["pager", "beeper", "notify"] },
  { char: "🗄️", name: "file cabinet", keywords: ["cabinet", "archive", "storage", "files"] },
  { char: "🗃️", name: "card file box", keywords: ["card", "index", "files", "box"] },
  { char: "🗂️", name: "card index dividers", keywords: ["files", "index", "registry", "tabs"] },
  { char: "📇", name: "card index", keywords: ["index", "card", "contacts"] },
  { char: "📋", name: "clipboard", keywords: ["clipboard", "list", "tasks", "copy"] },
  { char: "📌", name: "pushpin", keywords: ["pin", "mark", "location", "pinned"] },
  { char: "📍", name: "round pushpin", keywords: ["pin", "location", "mark"] },
  { char: "📎", name: "paperclip", keywords: ["paperclip", "attach", "clip"] },
  { char: "🖇️", name: "linked paperclips", keywords: ["link", "attach", "connect"] },
  { char: "📏", name: "straight ruler", keywords: ["ruler", "measure"] },
  { char: "📐", name: "triangular ruler", keywords: ["ruler", "measure", "angle"] },
  { char: "✂️", name: "scissors", keywords: ["scissors", "cut", "snip"] },
  { char: "🗑️", name: "wastebasket", keywords: ["trash", "delete", "remove", "bin"] },
  { char: "🔓", name: "unlocked", keywords: ["unlock", "open", "access"] },
  { char: "🔐", name: "locked with key", keywords: ["secure", "key", "encrypted"] },
  { char: "🔏", name: "locked with pen", keywords: ["sign", "secure", "contract"] },
  { char: "🗝️", name: "old key", keywords: ["key", "access", "legacy"] },
  { char: "🔑", name: "key", keywords: ["key", "access", "secret", "credential"] },
  { char: "🛡️", name: "shield", keywords: ["shield", "security", "protect", "defense"] },
  { char: "🔨", name: "hammer", keywords: ["hammer", "build", "fix", "tool"] },
  { char: "⚒️", name: "hammer and pick", keywords: ["tools", "build", "mine"] },
  { char: "🪛", name: "screwdriver", keywords: ["screwdriver", "tool", "fix", "build"] },
  { char: "🔩", name: "nut and bolt", keywords: ["bolt", "nut", "hardware", "fasten"] },
  { char: "⚙️", name: "gear", keywords: ["gear", "settings", "config", "mechanism"] },
  { char: "🧰", name: "toolbox", keywords: ["toolbox", "tools", "kit"] },
  { char: "🧲", name: "magnet", keywords: ["magnet", "attract", "pull"] },
  { char: "🪜", name: "ladder", keywords: ["ladder", "climb", "steps"] },
  { char: "🧱", name: "brick", keywords: ["brick", "wall", "build", "infrastructure"] },
  { char: "🏗️", name: "building construction", keywords: ["construction", "build", "crane", "infra"] },
  { char: "🚚", name: "delivery truck", keywords: ["truck", "ship", "delivery", "logistics"] },
  { char: "🏷️", name: "label", keywords: ["label", "tag", "price", "name"] },
  { char: "📮", name: "postbox", keywords: ["mail", "post", "submit", "box"] },
  { char: "📬", name: "open mailbox with raised flag", keywords: ["mail", "inbox", "notify"] },
  { char: "📭", name: "open mailbox with lowered flag", keywords: ["mail", "inbox", "empty"] },
  { char: "✉️", name: "envelope", keywords: ["email", "mail", "message"] },
  { char: "📧", name: "e-mail", keywords: ["email", "mail", "message", "send"] },
  { char: "📤", name: "outbox tray", keywords: ["outbox", "send", "upload"] },
  { char: "📥", name: "inbox tray", keywords: ["inbox", "receive", "download"] },
  { char: "🔬", name: "microscope", keywords: ["microscope", "science", "lab", "research"] },
  { char: "🧫", name: "petri dish", keywords: ["lab", "culture", "science", "experiment"] },
  { char: "⚗️", name: "alembic", keywords: ["chemistry", "lab", "distill", "science"] },
  { char: "🧬", name: "dna", keywords: ["dna", "genome", "biology", "science"] },
  { char: "📊", name: "bar chart", keywords: ["chart", "graph", "stats", "analytics"] },
  { char: "📈", name: "chart increasing", keywords: ["chart", "growth", "up", "trend", "analytics"] },
  { char: "📉", name: "chart decreasing", keywords: ["chart", "decline", "down", "trend"] },
  { char: "🧮", name: "abacus", keywords: ["abacus", "calculate", "count", "math"] },
  { char: "🔍", name: "magnifying glass tilted left", keywords: ["search", "find", "look", "zoom"] },
  { char: "🔎", name: "magnifying glass tilted right", keywords: ["search", "find", "look", "zoom"] },
  { char: "🗒️", name: "spiral notepad", keywords: ["notes", "memo", "pad"] },
  { char: "🗓️", name: "spiral calendar", keywords: ["calendar", "schedule", "date"] },
  { char: "📅", name: "calendar", keywords: ["calendar", "date", "schedule"] },
  { char: "📆", name: "tear-off calendar", keywords: ["calendar", "date"] },
  { char: "⏱️", name: "stopwatch", keywords: ["timer", "stopwatch", "time"] },
  { char: "⏲️", name: "timer clock", keywords: ["timer", "countdown", "clock"] },
  { char: "⏰", name: "alarm clock", keywords: ["alarm", "clock", "time", "reminder"] },
  { char: "🧭", name: "compass", keywords: ["compass", "direction", "navigate"] },
  { char: "🔗", name: "link", keywords: ["link", "chain", "connect", "url"] },
  { char: "⛓️", name: "chains", keywords: ["chain", "link", "connect", "security"] },
  { char: "🧯", name: "fire extinguisher", keywords: ["safety", "fire", "extinguish", "emergency"] },
  { char: "🚨", name: "police car light", keywords: ["alert", "warning", "emergency", "siren"] },
  { char: "🔦", name: "flashlight", keywords: ["flashlight", "torch", "light"] },
  { char: "🕯️", name: "candle", keywords: ["candle", "light", "flame"] },
  { char: "💡", name: "light bulb", keywords: ["idea", "light", "bulb", "bright"] },
];

const SYMBOLS_ENTRIES: EmojiEntry[] = [
  { char: "✅", name: "check mark button", keywords: ["check", "done", "ok", "yes"] },
  { char: "✔️", name: "check mark", keywords: ["check", "done", "ok"] },
  { char: "❌", name: "cross mark", keywords: ["cross", "no", "fail", "error"] },
  { char: "❎", name: "cross mark button", keywords: ["cross", "no", "fail"] },
  { char: "⚠️", name: "warning", keywords: ["warning", "alert", "caution"] },
  { char: "❗", name: "exclamation mark", keywords: ["exclamation", "alert", "important"] },
  { char: "❕", name: "white exclamation mark", keywords: ["exclamation", "alert"] },
  { char: "❓", name: "question mark", keywords: ["question", "help", "unknown"] },
  { char: "❔", name: "white question mark", keywords: ["question", "help"] },
  { char: "‼️", name: "double exclamation mark", keywords: ["exclamation", "emphasis"] },
  { char: "⁉️", name: "exclamation question mark", keywords: ["exclamation", "question", "surprise"] },
  { char: "🚫", name: "prohibited", keywords: ["prohibited", "no", "forbidden", "block"] },
  { char: "⛔", name: "no entry", keywords: ["no entry", "stop", "block"] },
  { char: "🔴", name: "red circle", keywords: ["red", "circle", "dot"] },
  { char: "🟠", name: "orange circle", keywords: ["orange", "circle", "dot"] },
  { char: "🟡", name: "yellow circle", keywords: ["yellow", "circle", "dot"] },
  { char: "🟢", name: "green circle", keywords: ["green", "circle", "dot"] },
  { char: "🔵", name: "blue circle", keywords: ["blue", "circle", "dot"] },
  { char: "🟣", name: "purple circle", keywords: ["purple", "circle", "dot"] },
  { char: "⚫", name: "black circle", keywords: ["black", "circle", "dot"] },
  { char: "⚪", name: "white circle", keywords: ["white", "circle", "dot"] },
  { char: "🟤", name: "brown circle", keywords: ["brown", "circle", "dot"] },
  { char: "🔶", name: "large orange diamond", keywords: ["diamond", "orange", "shape"] },
  { char: "🔷", name: "large blue diamond", keywords: ["diamond", "blue", "shape"] },
  { char: "🔺", name: "red triangle pointed up", keywords: ["triangle", "up", "shape"] },
  { char: "🔻", name: "red triangle pointed down", keywords: ["triangle", "down", "shape"] },
  { char: "⭐", name: "star", keywords: ["star", "favorite", "rating"] },
  { char: "🌟", name: "glowing star", keywords: ["star", "glow", "shine"] },
  { char: "💫", name: "dizzy", keywords: ["dizzy", "stars", "sparkle"] },
  { char: "🌠", name: "shooting star", keywords: ["shooting star", "wish", "comet"] },
  { char: "🔥", name: "fire", keywords: ["fire", "hot", "trending", "flame"] },
  { char: "🌩️", name: "cloud with lightning", keywords: ["storm", "lightning", "cloud"] },
  { char: "💥", name: "collision", keywords: ["collision", "boom", "impact"] },
  { char: "🎯", name: "direct hit", keywords: ["target", "goal", "bullseye", "focus"] },
  { char: "🚀", name: "rocket", keywords: ["rocket", "launch", "fast", "ship"] },
  { char: "🛸", name: "flying saucer", keywords: ["ufo", "alien", "saucer"] },
  { char: "➡️", name: "right arrow", keywords: ["arrow", "right", "next"] },
  { char: "⬅️", name: "left arrow", keywords: ["arrow", "left", "back"] },
  { char: "⬆️", name: "up arrow", keywords: ["arrow", "up"] },
  { char: "⬇️", name: "down arrow", keywords: ["arrow", "down"] },
  { char: "↗️", name: "up-right arrow", keywords: ["arrow", "diagonal", "up right"] },
  { char: "↘️", name: "down-right arrow", keywords: ["arrow", "diagonal", "down right"] },
  { char: "↙️", name: "down-left arrow", keywords: ["arrow", "diagonal", "down left"] },
  { char: "↖️", name: "up-left arrow", keywords: ["arrow", "diagonal", "up left"] },
  { char: "🔄", name: "counterclockwise arrows button", keywords: ["refresh", "sync", "reload"] },
  { char: "🔁", name: "repeat button", keywords: ["repeat", "loop", "cycle"] },
  { char: "🔂", name: "repeat single button", keywords: ["repeat", "once", "loop"] },
  { char: "⏩", name: "fast-forward button", keywords: ["fast forward", "skip", "next"] },
  { char: "⏪", name: "fast reverse button", keywords: ["rewind", "back", "previous"] },
  { char: "🔀", name: "shuffle tracks button", keywords: ["shuffle", "random", "mix"] },
  { char: "❤️", name: "red heart", keywords: ["heart", "love", "favorite"] },
  { char: "🧡", name: "orange heart", keywords: ["heart", "love", "orange"] },
  { char: "💛", name: "yellow heart", keywords: ["heart", "love", "yellow"] },
  { char: "💚", name: "green heart", keywords: ["heart", "love", "green"] },
  { char: "💙", name: "blue heart", keywords: ["heart", "love", "blue"] },
  { char: "💜", name: "purple heart", keywords: ["heart", "love", "purple"] },
  { char: "🖤", name: "black heart", keywords: ["heart", "love", "black"] },
  { char: "🤍", name: "white heart", keywords: ["heart", "love", "white"] },
  { char: "💔", name: "broken heart", keywords: ["heart", "broken", "sad"] },
  { char: "💯", name: "hundred points", keywords: ["hundred", "perfect", "score", "100"] },
  { char: "🔰", name: "japanese symbol for beginner", keywords: ["beginner", "new", "learner"] },
  { char: "♻️", name: "recycling symbol", keywords: ["recycle", "reuse", "green"] },
  { char: "⭕", name: "hollow red circle", keywords: ["circle", "ring", "empty"] },
  { char: "🔘", name: "radio button", keywords: ["radio", "selected", "option"] },
  { char: "🔲", name: "black square button", keywords: ["square", "button"] },
  { char: "🔳", name: "white square button", keywords: ["square", "button"] },
  { char: "▶️", name: "play button", keywords: ["play", "start", "run"] },
  { char: "⏸️", name: "pause button", keywords: ["pause", "hold"] },
  { char: "⏹️", name: "stop button", keywords: ["stop", "halt", "end"] },
];

const NATURE_ENTRIES: EmojiEntry[] = [
  { char: "🌱", name: "seedling", keywords: ["seedling", "plant", "grow", "new"] },
  { char: "🌲", name: "evergreen tree", keywords: ["tree", "pine", "forest"] },
  { char: "🌳", name: "deciduous tree", keywords: ["tree", "forest", "nature"] },
  { char: "🌴", name: "palm tree", keywords: ["palm", "tree", "tropical"] },
  { char: "🌵", name: "cactus", keywords: ["cactus", "desert", "plant"] },
  { char: "🌾", name: "sheaf of rice", keywords: ["rice", "grain", "harvest"] },
  { char: "🌷", name: "tulip", keywords: ["tulip", "flower", "spring"] },
  { char: "🌸", name: "cherry blossom", keywords: ["blossom", "flower", "spring"] },
  { char: "🌹", name: "rose", keywords: ["rose", "flower", "love"] },
  { char: "🌻", name: "sunflower", keywords: ["sunflower", "flower", "sun"] },
  { char: "🌼", name: "blossom", keywords: ["blossom", "flower"] },
  { char: "🍀", name: "four leaf clover", keywords: ["clover", "luck", "lucky"] },
  { char: "🍁", name: "maple leaf", keywords: ["leaf", "maple", "autumn"] },
  { char: "🍂", name: "fallen leaf", keywords: ["leaf", "autumn", "fall"] },
  { char: "🍃", name: "leaf fluttering in wind", keywords: ["leaf", "wind", "nature"] },
  { char: "🌊", name: "water wave", keywords: ["wave", "ocean", "sea", "water"] },
  { char: "🌈", name: "rainbow", keywords: ["rainbow", "colorful", "pride"] },
  { char: "☀️", name: "sun", keywords: ["sun", "sunny", "weather", "bright"] },
  { char: "🌤️", name: "sun behind small cloud", keywords: ["sun", "cloud", "weather"] },
  { char: "⛅", name: "sun behind cloud", keywords: ["sun", "cloud", "weather"] },
  { char: "🌥️", name: "sun behind large cloud", keywords: ["sun", "cloud", "weather"] },
  { char: "☁️", name: "cloud", keywords: ["cloud", "weather", "overcast"] },
  { char: "🌦️", name: "sun behind rain cloud", keywords: ["sun", "rain", "weather"] },
  { char: "🌧️", name: "cloud with rain", keywords: ["rain", "cloud", "weather"] },
  { char: "⛈️", name: "cloud with lightning and rain", keywords: ["storm", "rain", "lightning"] },
  { char: "❄️", name: "snowflake", keywords: ["snow", "cold", "winter"] },
  { char: "☃️", name: "snowman", keywords: ["snowman", "winter", "snow"] },
  { char: "⛄", name: "snowman without snow", keywords: ["snowman", "winter"] },
  { char: "🌬️", name: "wind face", keywords: ["wind", "blow", "air"] },
  { char: "🌪️", name: "tornado", keywords: ["tornado", "storm", "wind"] },
  { char: "🌫️", name: "fog", keywords: ["fog", "mist", "weather"] },
  { char: "🌙", name: "crescent moon", keywords: ["moon", "night", "crescent"] },
  { char: "🌕", name: "full moon", keywords: ["moon", "night", "full"] },
  { char: "🌑", name: "new moon", keywords: ["moon", "night", "dark"] },
  { char: "🪐", name: "ringed planet", keywords: ["planet", "saturn", "space"] },
  { char: "🌍", name: "globe showing europe-africa", keywords: ["globe", "world", "earth"] },
  { char: "🌎", name: "globe showing americas", keywords: ["globe", "world", "earth"] },
  { char: "🌏", name: "globe showing asia-australia", keywords: ["globe", "world", "earth"] },
  { char: "⛰️", name: "mountain", keywords: ["mountain", "peak", "hill"] },
  { char: "🏔️", name: "snow-capped mountain", keywords: ["mountain", "snow", "peak"] },
  { char: "🌋", name: "volcano", keywords: ["volcano", "eruption", "lava"] },
  { char: "🏕️", name: "camping", keywords: ["camping", "tent", "outdoors"] },
  { char: "🏝️", name: "desert island", keywords: ["island", "desert", "tropical"] },
  { char: "🏜️", name: "desert", keywords: ["desert", "sand", "dry"] },
];

const ANIMALS_ENTRIES: EmojiEntry[] = [
  { char: "🐶", name: "dog face", keywords: ["dog", "pet", "puppy"] },
  { char: "🐱", name: "cat face", keywords: ["cat", "pet", "kitten"] },
  { char: "🐭", name: "mouse face", keywords: ["mouse", "rodent"] },
  { char: "🐹", name: "hamster", keywords: ["hamster", "pet", "rodent"] },
  { char: "🐰", name: "rabbit face", keywords: ["rabbit", "bunny"] },
  { char: "🐻", name: "bear", keywords: ["bear", "wild"] },
  { char: "🐼", name: "panda", keywords: ["panda", "bear"] },
  { char: "🐨", name: "koala", keywords: ["koala", "bear"] },
  { char: "🐯", name: "tiger face", keywords: ["tiger", "wild", "cat"] },
  { char: "🦁", name: "lion", keywords: ["lion", "wild", "king"] },
  { char: "🐮", name: "cow face", keywords: ["cow", "farm"] },
  { char: "🐷", name: "pig face", keywords: ["pig", "farm"] },
  { char: "🐸", name: "frog", keywords: ["frog", "amphibian"] },
  { char: "🐵", name: "monkey face", keywords: ["monkey", "ape"] },
  { char: "🐔", name: "chicken", keywords: ["chicken", "farm", "bird"] },
  { char: "🐧", name: "penguin", keywords: ["penguin", "bird", "cold"] },
  { char: "🐦", name: "bird", keywords: ["bird", "fly"] },
  { char: "🐤", name: "baby chick", keywords: ["chick", "baby", "bird"] },
  { char: "🦆", name: "duck", keywords: ["duck", "bird", "water"] },
  { char: "🦅", name: "eagle", keywords: ["eagle", "bird", "raptor"] },
  { char: "🦉", name: "owl", keywords: ["owl", "bird", "night"] },
  { char: "🦇", name: "bat", keywords: ["bat", "night", "fly"] },
  { char: "🐺", name: "wolf", keywords: ["wolf", "wild"] },
  { char: "🐗", name: "boar", keywords: ["boar", "wild", "pig"] },
  { char: "🐴", name: "horse face", keywords: ["horse"] },
  { char: "🦄", name: "unicorn", keywords: ["unicorn", "fantasy", "magic"] },
  { char: "🐝", name: "honeybee", keywords: ["bee", "insect", "honey"] },
  { char: "🐛", name: "bug", keywords: ["bug", "insect"] },
  { char: "🦋", name: "butterfly", keywords: ["butterfly", "insect"] },
  { char: "🐌", name: "snail", keywords: ["snail", "slow"] },
  { char: "🐞", name: "lady beetle", keywords: ["ladybug", "insect"] },
  { char: "🐜", name: "ant", keywords: ["ant", "insect"] },
  { char: "🕷️", name: "spider", keywords: ["spider", "insect"] },
  { char: "🦂", name: "scorpion", keywords: ["scorpion", "desert"] },
  { char: "🐢", name: "turtle", keywords: ["turtle", "slow", "shell"] },
  { char: "🐍", name: "snake", keywords: ["snake", "reptile"] },
  { char: "🦎", name: "lizard", keywords: ["lizard", "reptile"] },
  { char: "🐙", name: "octopus", keywords: ["octopus", "sea"] },
  { char: "🦑", name: "squid", keywords: ["squid", "sea"] },
  { char: "🦀", name: "crab", keywords: ["crab", "sea"] },
  { char: "🦞", name: "lobster", keywords: ["lobster", "sea"] },
  { char: "🐠", name: "tropical fish", keywords: ["fish", "tropical", "sea"] },
  { char: "🐟", name: "fish", keywords: ["fish", "sea"] },
  { char: "🐬", name: "dolphin", keywords: ["dolphin", "sea"] },
  { char: "🐳", name: "spouting whale", keywords: ["whale", "sea"] },
  { char: "🐋", name: "whale", keywords: ["whale", "sea"] },
  { char: "🦈", name: "shark", keywords: ["shark", "sea"] },
  { char: "🐊", name: "crocodile", keywords: ["crocodile", "reptile"] },
  { char: "🐘", name: "elephant", keywords: ["elephant", "wild"] },
  { char: "🦏", name: "rhinoceros", keywords: ["rhino", "wild"] },
  { char: "🦛", name: "hippopotamus", keywords: ["hippo", "wild"] },
  { char: "🐫", name: "two-hump camel", keywords: ["camel", "desert"] },
  { char: "🦒", name: "giraffe", keywords: ["giraffe", "wild"] },
  { char: "🦘", name: "kangaroo", keywords: ["kangaroo", "wild"] },
  { char: "🐎", name: "horse", keywords: ["horse", "ride"] },
  { char: "🐄", name: "cow", keywords: ["cow", "farm"] },
  { char: "🐑", name: "ewe", keywords: ["sheep", "farm"] },
  { char: "🐐", name: "goat", keywords: ["goat", "farm"] },
  { char: "🐓", name: "rooster", keywords: ["rooster", "farm"] },
  { char: "🦃", name: "turkey", keywords: ["turkey", "farm"] },
  { char: "🐇", name: "rabbit", keywords: ["rabbit", "bunny"] },
  { char: "🦝", name: "raccoon", keywords: ["raccoon", "wild"] },
];

const FOOD_ENTRIES: EmojiEntry[] = [
  { char: "🍏", name: "green apple", keywords: ["apple", "fruit", "green"] },
  { char: "🍎", name: "red apple", keywords: ["apple", "fruit", "red"] },
  { char: "🍐", name: "pear", keywords: ["pear", "fruit"] },
  { char: "🍊", name: "tangerine", keywords: ["tangerine", "orange", "fruit"] },
  { char: "🍋", name: "lemon", keywords: ["lemon", "fruit", "sour"] },
  { char: "🍌", name: "banana", keywords: ["banana", "fruit"] },
  { char: "🍉", name: "watermelon", keywords: ["watermelon", "fruit"] },
  { char: "🍇", name: "grapes", keywords: ["grapes", "fruit", "wine"] },
  { char: "🍓", name: "strawberry", keywords: ["strawberry", "fruit"] },
  { char: "🫐", name: "blueberries", keywords: ["blueberry", "fruit"] },
  { char: "🍈", name: "melon", keywords: ["melon", "fruit"] },
  { char: "🍒", name: "cherries", keywords: ["cherries", "fruit"] },
  { char: "🍑", name: "peach", keywords: ["peach", "fruit"] },
  { char: "🥝", name: "kiwi fruit", keywords: ["kiwi", "fruit"] },
  { char: "🍅", name: "tomato", keywords: ["tomato", "vegetable"] },
  { char: "🥑", name: "avocado", keywords: ["avocado", "fruit"] },
  { char: "🥦", name: "broccoli", keywords: ["broccoli", "vegetable"] },
  { char: "🥕", name: "carrot", keywords: ["carrot", "vegetable"] },
  { char: "🌽", name: "ear of corn", keywords: ["corn", "vegetable"] },
  { char: "🌶️", name: "hot pepper", keywords: ["pepper", "spicy", "hot"] },
  { char: "🥔", name: "potato", keywords: ["potato", "vegetable"] },
  { char: "🍞", name: "bread", keywords: ["bread", "food"] },
  { char: "🥐", name: "croissant", keywords: ["croissant", "bread", "pastry"] },
  { char: "🥯", name: "bagel", keywords: ["bagel", "bread"] },
  { char: "🧀", name: "cheese wedge", keywords: ["cheese", "dairy"] },
  { char: "🍳", name: "cooking", keywords: ["egg", "cooking", "frying pan"] },
  { char: "🥞", name: "pancakes", keywords: ["pancakes", "breakfast"] },
  { char: "🍔", name: "hamburger", keywords: ["burger", "fast food"] },
  { char: "🍟", name: "french fries", keywords: ["fries", "fast food"] },
  { char: "🍕", name: "pizza", keywords: ["pizza", "fast food"] },
  { char: "🌭", name: "hot dog", keywords: ["hot dog", "fast food"] },
  { char: "🥪", name: "sandwich", keywords: ["sandwich", "food"] },
  { char: "🌮", name: "taco", keywords: ["taco", "mexican"] },
  { char: "🍣", name: "sushi", keywords: ["sushi", "japanese"] },
  { char: "🍜", name: "steaming bowl", keywords: ["noodles", "ramen", "soup"] },
  { char: "🍰", name: "shortcake", keywords: ["cake", "dessert"] },
  { char: "🎂", name: "birthday cake", keywords: ["cake", "birthday", "celebration"] },
  { char: "🍩", name: "doughnut", keywords: ["donut", "dessert"] },
  { char: "🍪", name: "cookie", keywords: ["cookie", "dessert"] },
  { char: "🍫", name: "chocolate bar", keywords: ["chocolate", "dessert"] },
  { char: "☕", name: "hot beverage", keywords: ["coffee", "tea", "drink"] },
  { char: "🍵", name: "teacup without handle", keywords: ["tea", "drink"] },
  { char: "🥤", name: "cup with straw", keywords: ["cup", "drink", "soda"] },
  { char: "🍺", name: "beer mug", keywords: ["beer", "drink"] },
  { char: "🍷", name: "wine glass", keywords: ["wine", "drink"] },
  { char: "🧃", name: "beverage box", keywords: ["juice", "drink", "box"] },
];

const ACTIVITY_ENTRIES: EmojiEntry[] = [
  { char: "⚽", name: "soccer ball", keywords: ["soccer", "football", "sport"] },
  { char: "🏀", name: "basketball", keywords: ["basketball", "sport"] },
  { char: "🏈", name: "american football", keywords: ["football", "sport"] },
  { char: "⚾", name: "baseball", keywords: ["baseball", "sport"] },
  { char: "🎾", name: "tennis", keywords: ["tennis", "sport"] },
  { char: "🏐", name: "volleyball", keywords: ["volleyball", "sport"] },
  { char: "🏉", name: "rugby football", keywords: ["rugby", "sport"] },
  { char: "🎱", name: "pool 8 ball", keywords: ["billiards", "pool", "game"] },
  { char: "🏓", name: "ping pong", keywords: ["ping pong", "table tennis"] },
  { char: "🏸", name: "badminton", keywords: ["badminton", "sport"] },
  { char: "🥊", name: "boxing glove", keywords: ["boxing", "fight", "sport"] },
  { char: "🥋", name: "martial arts uniform", keywords: ["martial arts", "karate"] },
  { char: "🎿", name: "skis", keywords: ["ski", "winter", "sport"] },
  { char: "🏂", name: "snowboarder", keywords: ["snowboard", "winter", "sport"] },
  { char: "🏄", name: "person surfing", keywords: ["surf", "wave", "sport"] },
  { char: "🚴", name: "person biking", keywords: ["bike", "cycling", "sport"] },
  { char: "🏋️", name: "person lifting weights", keywords: ["gym", "weights", "workout"] },
  { char: "🤸", name: "person cartwheeling", keywords: ["gymnastics", "cartwheel"] },
  { char: "🧗", name: "person climbing", keywords: ["climbing", "sport"] },
  { char: "🏆", name: "trophy", keywords: ["trophy", "award", "win"] },
  { char: "🥇", name: "1st place medal", keywords: ["gold", "medal", "first", "award"] },
  { char: "🥈", name: "2nd place medal", keywords: ["silver", "medal", "second", "award"] },
  { char: "🥉", name: "3rd place medal", keywords: ["bronze", "medal", "third", "award"] },
  { char: "🎖️", name: "military medal", keywords: ["medal", "award", "honor"] },
  { char: "🏅", name: "sports medal", keywords: ["medal", "award", "sport"] },
  { char: "🎮", name: "video game", keywords: ["game", "controller", "play"] },
  { char: "🕹️", name: "joystick", keywords: ["joystick", "game", "arcade"] },
  { char: "🎲", name: "game die", keywords: ["dice", "game", "chance"] },
  { char: "♟️", name: "chess pawn", keywords: ["chess", "pawn", "strategy"] },
  { char: "🧩", name: "puzzle piece", keywords: ["puzzle", "piece"] },
  { char: "🃏", name: "joker", keywords: ["joker", "card"] },
  { char: "🎳", name: "bowling", keywords: ["bowling", "sport", "game"] },
  { char: "🎵", name: "musical note", keywords: ["music", "note"] },
  { char: "🎶", name: "musical notes", keywords: ["music", "notes"] },
  { char: "🎤", name: "microphone", keywords: ["microphone", "sing", "music"] },
  { char: "🎧", name: "headphone", keywords: ["headphones", "music", "audio"] },
  { char: "🎸", name: "guitar", keywords: ["guitar", "music"] },
  { char: "🎹", name: "musical keyboard", keywords: ["keyboard", "music", "piano"] },
  { char: "🥁", name: "drum", keywords: ["drum", "music"] },
  { char: "🎺", name: "trumpet", keywords: ["trumpet", "music"] },
  { char: "🎻", name: "violin", keywords: ["violin", "music"] },
  { char: "🎬", name: "clapper board", keywords: ["movie", "film", "action"] },
];

const TRAVEL_ENTRIES: EmojiEntry[] = [
  { char: "🚗", name: "automobile", keywords: ["car", "automobile", "drive"] },
  { char: "🚕", name: "taxi", keywords: ["taxi", "cab"] },
  { char: "🚙", name: "sport utility vehicle", keywords: ["suv", "car"] },
  { char: "🚌", name: "bus", keywords: ["bus", "transit"] },
  { char: "🚎", name: "trolleybus", keywords: ["trolleybus", "transit"] },
  { char: "🏎️", name: "racing car", keywords: ["race", "car", "fast"] },
  { char: "🚓", name: "police car", keywords: ["police", "car"] },
  { char: "🚑", name: "ambulance", keywords: ["ambulance", "emergency"] },
  { char: "🚒", name: "fire engine", keywords: ["fire truck", "emergency"] },
  { char: "🚐", name: "minibus", keywords: ["minibus", "transit"] },
  { char: "🚛", name: "articulated lorry", keywords: ["truck", "lorry", "shipping"] },
  { char: "🚜", name: "tractor", keywords: ["tractor", "farm"] },
  { char: "🛵", name: "motor scooter", keywords: ["scooter", "ride"] },
  { char: "🏍️", name: "motorcycle", keywords: ["motorcycle", "ride"] },
  { char: "🚲", name: "bicycle", keywords: ["bike", "bicycle", "ride"] },
  { char: "🛴", name: "kick scooter", keywords: ["scooter", "ride"] },
  { char: "🚂", name: "locomotive", keywords: ["train", "locomotive"] },
  { char: "🚆", name: "train", keywords: ["train", "rail"] },
  { char: "🚇", name: "metro", keywords: ["metro", "subway"] },
  { char: "🚊", name: "tram", keywords: ["tram", "transit"] },
  { char: "✈️", name: "airplane", keywords: ["airplane", "flight", "travel"] },
  { char: "🛫", name: "airplane departure", keywords: ["flight", "departure", "travel"] },
  { char: "🛬", name: "airplane arrival", keywords: ["flight", "arrival", "travel"] },
  { char: "🚁", name: "helicopter", keywords: ["helicopter", "fly"] },
  { char: "🛶", name: "canoe", keywords: ["canoe", "boat"] },
  { char: "⛵", name: "sailboat", keywords: ["sailboat", "boat", "sea"] },
  { char: "🚤", name: "speedboat", keywords: ["speedboat", "boat"] },
  { char: "🛳️", name: "passenger ship", keywords: ["ship", "cruise", "sea"] },
  { char: "⚓", name: "anchor", keywords: ["anchor", "ship", "sea"] },
  { char: "🚢", name: "ship", keywords: ["ship", "sea", "boat"] },
  { char: "🏠", name: "house", keywords: ["house", "home"] },
  { char: "🏡", name: "house with garden", keywords: ["house", "home", "garden"] },
  { char: "🏢", name: "office building", keywords: ["office", "building"] },
  { char: "🏣", name: "japanese post office", keywords: ["post office", "mail"] },
  { char: "🏥", name: "hospital", keywords: ["hospital", "medical"] },
  { char: "🏦", name: "bank", keywords: ["bank", "finance"] },
  { char: "🏨", name: "hotel", keywords: ["hotel", "travel"] },
  { char: "🏩", name: "love hotel", keywords: ["hotel", "travel"] },
  { char: "🏪", name: "convenience store", keywords: ["store", "shop"] },
  { char: "🏫", name: "school", keywords: ["school", "education"] },
  { char: "🏬", name: "department store", keywords: ["store", "shop", "mall"] },
  { char: "🏭", name: "factory", keywords: ["factory", "industry"] },
  { char: "🗼", name: "tokyo tower", keywords: ["tower", "landmark", "tokyo"] },
  { char: "🗽", name: "statue of liberty", keywords: ["statue", "landmark", "new york"] },
  { char: "🕌", name: "mosque", keywords: ["mosque", "religion"] },
  { char: "🛕", name: "hindu temple", keywords: ["temple", "religion"] },
  { char: "⛪", name: "church", keywords: ["church", "religion"] },
];

const PEOPLE_ENTRIES: EmojiEntry[] = [
  { char: "🙂", name: "slightly smiling face", keywords: ["smile", "happy", "face"] },
  { char: "😀", name: "grinning face", keywords: ["grin", "happy", "face"] },
  { char: "😃", name: "grinning face with big eyes", keywords: ["grin", "happy", "face"] },
  { char: "😄", name: "grinning face with smiling eyes", keywords: ["grin", "happy", "face"] },
  { char: "😁", name: "beaming face with smiling eyes", keywords: ["happy", "grin", "face"] },
  { char: "😆", name: "grinning squinting face", keywords: ["laugh", "happy", "face"] },
  { char: "😅", name: "grinning face with sweat", keywords: ["laugh", "relief", "face"] },
  { char: "🤣", name: "rolling on the floor laughing", keywords: ["laugh", "funny", "face"] },
  { char: "😂", name: "face with tears of joy", keywords: ["laugh", "funny", "face"] },
  { char: "🙃", name: "upside-down face", keywords: ["silly", "face"] },
  { char: "😉", name: "winking face", keywords: ["wink", "face"] },
  { char: "😊", name: "smiling face with smiling eyes", keywords: ["smile", "happy", "face"] },
  { char: "😇", name: "smiling face with halo", keywords: ["angel", "innocent", "face"] },
  { char: "😍", name: "smiling face with heart-eyes", keywords: ["love", "face"] },
  { char: "🤩", name: "star-struck", keywords: ["excited", "wow", "face"] },
  { char: "😘", name: "face blowing a kiss", keywords: ["kiss", "love", "face"] },
  { char: "😗", name: "kissing face", keywords: ["kiss", "face"] },
  { char: "😋", name: "face savoring food", keywords: ["yum", "tasty", "face"] },
  { char: "😛", name: "face with tongue", keywords: ["tongue", "playful", "face"] },
  { char: "😜", name: "winking face with tongue", keywords: ["playful", "face"] },
  { char: "🤪", name: "zany face", keywords: ["crazy", "goofy", "face"] },
  { char: "😝", name: "squinting face with tongue", keywords: ["playful", "face"] },
  { char: "🤑", name: "money-mouth face", keywords: ["money", "rich", "face"] },
  { char: "🤗", name: "hugging face", keywords: ["hug", "face"] },
  { char: "🤔", name: "thinking face", keywords: ["think", "hmm", "face"] },
  { char: "🤐", name: "zipper-mouth face", keywords: ["quiet", "secret", "face"] },
  { char: "😐", name: "neutral face", keywords: ["neutral", "meh", "face"] },
  { char: "😑", name: "expressionless face", keywords: ["blank", "face"] },
  { char: "😶", name: "face without mouth", keywords: ["silent", "face"] },
  { char: "😏", name: "smirking face", keywords: ["smirk", "face"] },
  { char: "😒", name: "unamused face", keywords: ["unamused", "meh", "face"] },
  { char: "🙄", name: "face with rolling eyes", keywords: ["eyeroll", "annoyed", "face"] },
  { char: "😬", name: "grimacing face", keywords: ["grimace", "awkward", "face"] },
  { char: "🤥", name: "lying face", keywords: ["lie", "pinocchio", "face"] },
  { char: "😌", name: "relieved face", keywords: ["relieved", "face"] },
  { char: "😔", name: "pensive face", keywords: ["sad", "pensive", "face"] },
  { char: "😪", name: "sleepy face", keywords: ["sleepy", "tired", "face"] },
  { char: "🤤", name: "drooling face", keywords: ["drool", "face"] },
  { char: "😴", name: "sleeping face", keywords: ["sleep", "zzz", "face"] },
  { char: "😷", name: "face with medical mask", keywords: ["sick", "mask", "face"] },
  { char: "🤒", name: "face with thermometer", keywords: ["sick", "ill", "face"] },
  { char: "🥳", name: "partying face", keywords: ["party", "celebrate", "face"] },
  { char: "😎", name: "smiling face with sunglasses", keywords: ["cool", "sunglasses", "face"] },
  { char: "🤓", name: "nerd face", keywords: ["nerd", "geek", "face"] },
  { char: "🧐", name: "face with monocle", keywords: ["monocle", "inspect", "face"] },
  { char: "😕", name: "confused face", keywords: ["confused", "face"] },
  { char: "😟", name: "worried face", keywords: ["worried", "face"] },
  { char: "🙁", name: "slightly frowning face", keywords: ["frown", "sad", "face"] },
  { char: "😮", name: "face with open mouth", keywords: ["surprised", "face"] },
  { char: "😲", name: "astonished face", keywords: ["shocked", "face"] },
  { char: "😳", name: "flushed face", keywords: ["blush", "embarrassed", "face"] },
  { char: "🥺", name: "pleading face", keywords: ["pleading", "puppy eyes", "face"] },
  { char: "😢", name: "crying face", keywords: ["cry", "sad", "face"] },
  { char: "😭", name: "loudly crying face", keywords: ["cry", "sob", "face"] },
  { char: "😱", name: "face screaming in fear", keywords: ["scared", "fear", "face"] },
  { char: "😡", name: "pouting face", keywords: ["angry", "mad", "face"] },
  { char: "🤬", name: "face with symbols on mouth", keywords: ["angry", "curse", "face"] },
  { char: "👋", name: "waving hand", keywords: ["wave", "hello", "hand"] },
  { char: "🤝", name: "handshake", keywords: ["handshake", "deal", "agree"] },
  { char: "👍", name: "thumbs up", keywords: ["thumbs up", "like", "approve"] },
  { char: "👎", name: "thumbs down", keywords: ["thumbs down", "dislike"] },
  { char: "👏", name: "clapping hands", keywords: ["clap", "applause"] },
  { char: "🙌", name: "raising hands", keywords: ["celebrate", "hooray", "hands"] },
  { char: "🤲", name: "palms up together", keywords: ["hands", "support"] },
  { char: "🙏", name: "folded hands", keywords: ["pray", "thanks", "please"] },
  { char: "👌", name: "ok hand", keywords: ["ok", "hand", "perfect"] },
  { char: "✌️", name: "victory hand", keywords: ["peace", "victory", "hand"] },
  { char: "🤞", name: "crossed fingers", keywords: ["luck", "fingers crossed"] },
  { char: "👊", name: "oncoming fist", keywords: ["fist", "bump", "punch"] },
  { char: "✊", name: "raised fist", keywords: ["fist", "power", "solidarity"] },
];

const FLAGS_ENTRIES: EmojiEntry[] = [
  { char: "🏁", name: "chequered flag", keywords: ["flag", "finish", "race"] },
  { char: "🚩", name: "triangular flag", keywords: ["flag", "marker"] },
  { char: "🏴‍☠️", name: "pirate flag", keywords: ["flag", "pirate"] },
  { char: "🏳️‍🌈", name: "rainbow flag", keywords: ["flag", "pride", "rainbow"] },
  { char: "🇺🇸", name: "flag: united states", keywords: ["flag", "usa", "united states"] },
  { char: "🇬🇧", name: "flag: united kingdom", keywords: ["flag", "uk", "united kingdom", "britain"] },
  { char: "🇩🇪", name: "flag: germany", keywords: ["flag", "germany"] },
  { char: "🇫🇷", name: "flag: france", keywords: ["flag", "france"] },
  { char: "🇪🇸", name: "flag: spain", keywords: ["flag", "spain"] },
  { char: "🇮🇹", name: "flag: italy", keywords: ["flag", "italy"] },
  { char: "🇯🇵", name: "flag: japan", keywords: ["flag", "japan"] },
  { char: "🇰🇷", name: "flag: south korea", keywords: ["flag", "korea"] },
  { char: "🇨🇳", name: "flag: china", keywords: ["flag", "china"] },
  { char: "🇮🇳", name: "flag: india", keywords: ["flag", "india"] },
  { char: "🇧🇷", name: "flag: brazil", keywords: ["flag", "brazil"] },
  { char: "🇨🇦", name: "flag: canada", keywords: ["flag", "canada"] },
  { char: "🇦🇺", name: "flag: australia", keywords: ["flag", "australia"] },
  { char: "🇲🇽", name: "flag: mexico", keywords: ["flag", "mexico"] },
  { char: "🇳🇱", name: "flag: netherlands", keywords: ["flag", "netherlands"] },
  { char: "🇸🇪", name: "flag: sweden", keywords: ["flag", "sweden"] },
  { char: "🇨🇭", name: "flag: switzerland", keywords: ["flag", "switzerland"] },
  { char: "🇵🇹", name: "flag: portugal", keywords: ["flag", "portugal"] },
  { char: "🇷🇺", name: "flag: russia", keywords: ["flag", "russia"] },
  { char: "🇿🇦", name: "flag: south africa", keywords: ["flag", "south africa"] },
  { char: "🇦🇷", name: "flag: argentina", keywords: ["flag", "argentina"] },
];

export const EMOJI_GROUPS: EmojiGroup[] = [
  { id: "suggested", label: "Suggested", glyph: "📦", entries: SUGGESTED_ENTRIES },
  { id: "tools", label: "Tools & tech", glyph: "🛠️", entries: TOOLS_ENTRIES },
  { id: "symbols", label: "Symbols", glyph: "✨", entries: SYMBOLS_ENTRIES },
  { id: "nature", label: "Nature", glyph: "🌿", entries: NATURE_ENTRIES },
  { id: "animals", label: "Animals", glyph: "🦊", entries: ANIMALS_ENTRIES },
  { id: "food", label: "Food & drink", glyph: "☕", entries: FOOD_ENTRIES },
  { id: "activity", label: "Activity", glyph: "🎯", entries: ACTIVITY_ENTRIES },
  { id: "travel", label: "Travel & places", glyph: "🚀", entries: TRAVEL_ENTRIES },
  { id: "people", label: "Smileys & people", glyph: "🙂", entries: PEOPLE_ENTRIES },
  { id: "flags", label: "Flags", glyph: "🏁", entries: FLAGS_ENTRIES },
];

function findExactChar(char: string): EmojiEntry | undefined {
  for (const group of EMOJI_GROUPS) {
    const hit = group.entries.find((e) => e.char === char);
    if (hit) return hit;
  }
  return undefined;
}

/**
 * Every whitespace-separated token of `query` must prefix-match a word of an
 * entry's name or one of its keywords. Deduped by char across all groups,
 * capped at 96 results.
 */
export function searchEmoji(query: string): EmojiEntry[] {
  const trimmedRaw = query.trim();
  const tokens = trimmedRaw.toLowerCase().split(/\s+/).filter(Boolean);
  if (tokens.length === 0) return [];
  const seen = new Set<string>();
  const out: EmojiEntry[] = [];
  // A pasted dataset emoji is an EXACT char match — surface its own named
  // tile first, ahead of the token search below, so it doesn't fall behind
  // unrelated matches or get eclipsed by the dashed "Use as typed" tile
  // (which only ever covers a char with NO dataset entry).
  const exact = findExactChar(trimmedRaw);
  if (exact) {
    seen.add(exact.char);
    out.push(exact);
  }
  for (const group of EMOJI_GROUPS) {
    for (const entry of group.entries) {
      if (seen.has(entry.char)) continue;
      const words = [
        ...entry.name.toLowerCase().split(/\s+/),
        ...entry.keywords.map((k) => k.toLowerCase()),
      ];
      const matchesAll = tokens.every((tok) =>
        words.some((w) => w.startsWith(tok)),
      );
      if (matchesAll) {
        seen.add(entry.char);
        out.push(entry);
        if (out.length >= 96) return out;
      }
    }
  }
  return out;
}

