"""Codex permission adapter: `~/.codex/config.toml` typed knobs (project trust,
approval policy, sandbox mode) plus the hub-owned Starlark `skill-hub.rules`
command-rules file. Split out of `permission_adapters.py` (wave 22a).
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Optional

from skill_hub.domain.harnesses.harness_adapter_api import PermissionCommandRule, thaw_native_value
from skill_hub.domain.permissions.permission_adapter_base import (
    DirectoryEndpoint,
    DirectoryPlan,
    NativeDirectoryMutation,
    NativeWrite,
    SkipReason,
    TranslateResult,
    ValidationResult,
    WorktreeAccessStatus,
    _atomic_replace,
    _backup_once_per_session,
    _bash_prefix_tokens,
    _detect_risks_for_translate,
    _kind_feature,
    apply_directory_cleanup,
    plan_directory_cleanup,
)
from skill_hub.domain.permissions.permissions import (
    DirectoryLedgerIdentity,
    GlobalScope,
    NormalizedPermissions,
    PermissionFeature,
    ProjectScope,
    Rule,
    Scope,
    delete_directory_sidecar,
    delete_sidecar,
    read_directory_sidecar,
    read_sidecar,
    write_directory_sidecar,
    write_sidecar,
)
from skill_hub.infrastructure.harnesses.harness_bundled_permissions import CodexPermissionCodec

# ─────────────────────────────────────────────────────────────────────────────
# Codex pattern-mapping helpers (registry Bash rules ⇄ Starlark prefix_rule)
# ─────────────────────────────────────────────────────────────────────────────


_CODEX_GLOBAL = Path("~/.codex/config.toml")

_CODEX_CAPS = {
    PermissionFeature.SANDBOX_MODE,
    PermissionFeature.APPROVAL_POLICY,
    PermissionFeature.PROJECT_TRUST,
    PermissionFeature.TOOL_ALLOWLIST,
    PermissionFeature.TOOL_DENYLIST,
    PermissionFeature.TOOL_ASK,
}

# kind ↔ Codex decision, both directions (translate + discover).
_KIND_TO_DECISION = {"allow": "allow", "ask": "prompt", "deny": "forbidden"}
_DECISION_TO_KIND = {v: k for k, v in _KIND_TO_DECISION.items()}

_CODEX_RULES_HEADER = "# Generated by Skill Hub — do not edit; managed via the hub registry."
_RULES_SIDECAR_KIND = "rules"  # sidecar `kind` for the skill-hub.rules write (D9)

_PERMISSION_CODEC = CodexPermissionCodec()


def _emit_prefix_rule_line(tokens: list[str], decision: str, kind: str, pattern: str) -> str:
    """Compatibility wrapper for callers of the former host helper."""
    return _PERMISSION_CODEC.render_rule(PermissionCommandRule(tuple(tokens), kind, pattern))


def _render_codex_rules_file(entries: list[tuple]) -> str:
    """Compatibility wrapper for the former tuple-based renderer."""
    rules = tuple(
        PermissionCommandRule(tuple(tokens), kind, pattern)
        for tokens, _decision, kind, pattern in entries
    )
    return _PERMISSION_CODEC.encode(rules)


def _codex_rules_target(scope: Scope) -> Path:
    """`~/.codex/rules/skill-hub.rules` (global) or `<repo>/.codex/rules/skill-hub.rules`."""
    if isinstance(scope, GlobalScope):
        return Path("~/.codex/rules/skill-hub.rules").expanduser()
    return Path(scope.path) / ".codex" / "rules" / "skill-hub.rules"


def _codex_default_rules_target(scope: Scope) -> Path:
    """The user's TUI-owned `default.rules` for a scope (read/import only)."""
    if isinstance(scope, GlobalScope):
        return Path("~/.codex/rules/default.rules").expanduser()
    return Path(scope.path) / ".codex" / "rules" / "default.rules"


def _nonempty_literal(node) -> bool:
    return _PERMISSION_CODEC.nonempty_literal(node)


def _parse_prefix_rules(text: str) -> list[dict]:
    """Compatibility wrapper returning the former candidate dictionaries."""
    out: list[dict] = []
    for observation in _PERMISSION_CODEC.decode(text):
        out.append(
            {
                "tokens": list(observation.tokens) if observation.tokens is not None else None,
                "decision": thaw_native_value(observation.native_decision),
                "justification": thaw_native_value(observation.justification),
                "has_match": observation.has_match,
                "lineno": observation.lineno,
                "end_lineno": observation.end_lineno,
                "importable": observation.importable,
                "reason": observation.reason,
            }
        )
    return out

def _prefix_rule_to_registry_pattern(tokens: list[str]) -> str:
    """`["git", "push"]` → `Bash(git push:*)`."""
    return f"Bash({' '.join(tokens)}:*)"


from skill_hub.hub_core import _TOMLKIT_MISSING_REASON, _tomlkit_missing

# ─────────────────────────────────────────────────────────────────────────────
# Codex adapter (TOML config + Starlark rules)
# ─────────────────────────────────────────────────────────────────────────────


class CodexPermissionAdapter:
    """Writes `~/.codex/config.toml` (typed knobs + project trust) AND a
    hub-owned Starlark rules file (`skill-hub.rules`) for translatable Bash
    command rules.

    Global scope: top-level keys (`approval_policy`, `sandbox_mode`) +
    `~/.codex/rules/skill-hub.rules`.
    Project scope: `[projects."<abs-path>"]` table with `trust_level = "trusted"`
    + `<repo>/.codex/rules/skill-hub.rules`.
    """

    def __init__(self, layout=None):
        self._layout = layout

    def target_files(self, scope: Scope, harness_id: str = "codex") -> Path:
        if harness_id != "codex":
            raise ValueError(f"CodexPermissionAdapter: unsupported harness {harness_id!r}")
        if self._layout is not None:
            if self._layout.permission_global_config is None:
                raise ValueError("permission target is unavailable in this operation")
            return Path(self._layout.permission_global_config)
        return Path(str(_CODEX_GLOBAL)).expanduser()

    def rules_file(self, scope: Scope) -> Path:
        if self._layout is not None and self._layout.permission_rules_dir is not None:
            if isinstance(scope, GlobalScope):
                return Path(self._layout.config_dir) / "rules" / "skill-hub.rules"
            return Path(scope.path) / self._layout.permission_rules_dir / "skill-hub.rules"
        if self._layout is not None:
            raise ValueError("permission rules target is unavailable in this operation")
        return _codex_rules_target(scope)

    def default_rules_file(self, scope: Scope) -> Path:
        if self._layout is not None and self._layout.permission_default_rules is not None:
            if isinstance(scope, GlobalScope):
                return Path(self._layout.config_dir) / "rules" / "default.rules"
            return Path(scope.path) / self._layout.permission_default_rules
        if self._layout is not None:
            raise ValueError("default rules target is unavailable in this operation")
        return _codex_default_rules_target(scope)

    def capabilities(self) -> set:
        return set(_CODEX_CAPS)

    def validate(self, rule: Rule) -> ValidationResult:
        # Translatable iff it yields a bounded Bash prefix; everything else
        # (non-Bash tools, unbounded Bash(*)) is unsupported here.
        if not rule.pattern:
            return ValidationResult(ok=False, error="empty pattern")
        if rule.kind not in _KIND_TO_DECISION:
            return ValidationResult(ok=False, error=f"unknown kind {rule.kind!r}")
        if _bash_prefix_tokens(rule.pattern) is None:
            return ValidationResult(
                ok=False,
                error="Codex command rules require a bounded Bash prefix (Bash(<cmd>:*))",
            )
        return ValidationResult(ok=True)

    def _load_doc(self, path: Path):
        if _tomlkit_missing():
            # Environment-capability gap (dev/CI Python without tomlkit), NOT a
            # write failure: both callers already treat a None doc as "skip
            # this write" (return False) rather than crash the whole sync.
            print(
                f"warning: {_TOMLKIT_MISSING_REASON} — skipping Codex permission write",
                file=sys.stderr,
            )
            return None

        import tomlkit

        if not path.exists():
            return tomlkit.document()
        try:
            return tomlkit.parse(path.read_text())
        except Exception as e:
            print(f"warning: cannot parse {path}: {e} — skipping Codex permission write", file=sys.stderr)
            return None

    def translate(
        self,
        perms: NormalizedPermissions,
        scope: Scope,
        harness_id: str,
    ) -> TranslateResult:
        target = self.target_files(scope, harness_id)
        result = TranslateResult()

        def applicable(harnesses: Optional[list[str]]) -> bool:
            return harnesses is None or harness_id in harnesses

        # ── Partition allow/deny/ask into translatable prefix rules vs skips ──
        rule_entries: list[tuple] = []  # (tokens, decision, kind, pattern)
        has_command_rule = False
        for kind, rules in (
            ("allow", perms.allow),
            ("deny", perms.deny),
            ("ask", perms.ask),
        ):
            for r in rules:
                if not applicable(r.harnesses):
                    continue
                tokens = _bash_prefix_tokens(r.pattern)
                if tokens is None:
                    result.skipped.append(
                        SkipReason(
                            feature=_kind_feature(kind).value,
                            reason=(
                                "Codex command rules require a bounded Bash prefix "
                                "(Bash(<cmd>:*)); no prefix could be derived"
                            ),
                            rule_pattern=r.pattern,
                        )
                    )
                    # Dropping a security CONTROL (deny/ask) is a regression, not
                    # a dropped convenience — escalate to a risk finding.
                    if kind in ("deny", "ask"):
                        from skill_hub.domain.diagnostics import risks as _risks

                        result.risks.append(_risks.dropped_deny_finding(r.pattern, harness_id, kind))
                    continue
                rule_entries.append((tokens, _KIND_TO_DECISION[kind], kind, r.pattern))
                has_command_rule = True

        # Hooks are owned by the hook library + hooks sync stream (hooks-surface
        # D6); the permissions block no longer carries them and codex IS
        # hook-capable, so the retired DROPPED_HOOK skip/risk is no longer emitted.
        # Directory grants are reconciled in the same target transaction as
        # other Codex project permissions. The legacy root is supported when
        # no named profile selector is active.

        # Forward-compat: unknown `extras` keys are not recognised by this adapter.
        for extras_key in perms.extras.keys():
            result.skipped.append(
                SkipReason(
                    feature=extras_key,
                    reason=f"codex adapter does not recognise extras key {extras_key!r}",
                )
            )

        # ── config.toml payload (typed knobs + project trust) ──
        toml_managed: list[str] = []
        toml_payload: dict[str, Any] = {}
        trust_auto_granted = False

        if isinstance(scope, GlobalScope):
            if perms.approval_policy is not None:
                toml_payload["approval_policy"] = perms.approval_policy
                toml_managed.append("approval_policy")
            if perms.sandbox_mode is not None:
                toml_payload["sandbox_mode"] = perms.sandbox_mode
                toml_managed.append("sandbox_mode")
        elif isinstance(scope, ProjectScope):
            grant_trust = perms.project_trust is True
            # Auto-grant trust so Codex loads the project rules file (D5).
            if has_command_rule and not grant_trust:
                grant_trust = True
                trust_auto_granted = True
            if grant_trust:
                toml_payload["projects"] = {scope.path: {"trust_level": "trusted"}}
                toml_managed.append(f"projects.{_codex_project_key(scope.path)}.trust_level")

        # Prepend the base risk findings (the partition loop above may already
        # have appended DROPPED_DENY escalations — keep those).
        result.risks = _detect_risks_for_translate(perms, self.capabilities()) + result.risks

        if trust_auto_granted:
            warning = (
                f"Codex project trust auto-granted for {scope.name!r} "
                f"({scope.path}) so its command rules load — this also activates "
                f"any committed .codex/config.toml and project-local hooks."
            )
            result.warnings.append(warning)
            from skill_hub.domain.diagnostics import risks as _risks

            result.risks.append(
                _risks.RiskFinding(
                    code="CODEX_PROJECT_TRUST_GRANTED",
                    severity="warning",
                    explanation=(
                        "Writing project command rules auto-granted trust to the project's "
                        ".codex/ layer, activating any committed config.toml and hooks."
                    ),
                    detail=f"{scope.name} ({scope.path})",
                )
            )

        # ── Emit writes ──
        if toml_payload:
            result.writes.append(
                NativeWrite(
                    target_path=target,
                    payload=toml_payload,
                    managed_keys=toml_managed,
                    format="toml",
                )
            )

        if rule_entries:
            content = _PERMISSION_CODEC.encode(
                tuple(
                    PermissionCommandRule(tuple(tokens), kind, pattern)
                    for tokens, _decision, kind, pattern in rule_entries
                )
            )
            managed = [f"prefix_rule[{i}]" for i in range(len(rule_entries))]
            result.writes.append(
                NativeWrite(
                    target_path=self.rules_file(scope),
                    payload=content,
                    managed_keys=managed,
                    format="starlark",
                )
            )
        elif read_sidecar(harness_id, scope, _RULES_SIDECAR_KIND) is not None:
            # All translatable rules removed but a hub rules file still exists —
            # emit a deletion write so re-sync clears the stale file (no ghosts).
            result.writes.append(
                NativeWrite(
                    target_path=self.rules_file(scope),
                    payload=None,
                    managed_keys=[],
                    format="starlark",
                )
            )

        return result

    def _directory_context(self, project_config=None, user_config=None, managed_requirements=None):
        """Return the bounded selector evidence used for directory writes."""
        project_config = project_config or {}
        user_config = user_config or {}
        # Project selector wins. Keep the legacy sandbox selectors restrictive.
        if project_config.get("sandbox_mode") is not None or user_config.get("sandbox_mode") is not None:
            return ("unsupported", None)
        selector = project_config.get("default_permissions")
        if selector is None:
            selector = user_config.get("default_permissions")
        if selector in {":read-only", ":danger-full-access", "read-only", "danger-full-access", "danger", "unknown"}:
            return ("unsupported", None)
        if managed_requirements and managed_requirements.get("allowed_permission_profiles") is not None:
            return ("managed", None)
        if isinstance(selector, str) and selector:
            return ("profile", selector)
        return ("legacy", None)

    def plan_directories(self, scope, contributions, harness_id):
        target = self.target_files(scope, harness_id)
        family = "codex-legacy"
        state = "configured"
        if isinstance(scope, ProjectScope):
            project_cfg = Path(scope.path) / ".codex" / "config.toml"
            target = project_cfg
            user_cfg = self.target_files(scope, harness_id)
            try:
                import tomlkit

                project_doc = tomlkit.parse(project_cfg.read_text()) if project_cfg.exists() else {}
                user_doc = tomlkit.parse(user_cfg.read_text()) if user_cfg.exists() else {}
                managed = {}
                if self._layout is not None:
                    if self._layout.config_dir is None:
                        raise ValueError("Codex requirements path unavailable in operation")
                    req = Path(self._layout.config_dir) / "requirements.toml"
                else:
                    req = Path("~/.codex/requirements.toml").expanduser()
                if req.exists():
                    managed = dict(tomlkit.parse(req.read_text()))
                evidence, selected = self._directory_context(dict(project_doc), dict(user_doc), managed)
                if evidence == "profile" and selected:
                    project_profiles = project_doc.get("permissions") or {}
                    user_profiles = user_doc.get("permissions") or {}
                    profiles = {**dict(user_profiles), **dict(project_profiles)}
                    profile = profiles.get(selected) if hasattr(profiles, "get") else None
                    roots = profile.get("workspace_roots") if hasattr(profile, "get") else None
                    # A selected profile may be inherited from the user config
                    # while the project file has no table yet.  The project
                    # write creates that table after the bounded chain proves
                    # workspace-root writes are allowed.
                    if self._profile_allows_workspace_roots(selected, profiles) and (
                        roots is None or isinstance(roots, dict)
                    ):
                        target = project_cfg
                        family = f"codex-profile:{selected}"
                    else:
                        state = "unsupported"
                elif evidence in {"unsupported", "managed"}:
                    state = "unsupported"
            except Exception:
                state = "unsupported"
        key = (
            "sandbox_workspace_write.writable_roots"
            if family == "codex-legacy"
            else f"permissions.{family.split(':', 1)[1]}.workspace_roots"
        )
        return DirectoryPlan(
            target,
            key,
            tuple(contributions),
            family,
            state,
            None if state == "configured" else "CODEX_PROFILE_UNSUPPORTED",
        )

    @staticmethod
    def _profile_allows_workspace_roots(name, profiles):
        """Accept only a bounded named-profile chain with workspace-root writes."""
        seen = set()
        current = name
        while isinstance(current, str) and current not in seen:
            seen.add(current)
            if current == ":workspace":
                return True
            if current in {":read-only", ":danger-full-access", ":danger"}:
                return False
            profile = profiles.get(current)
            if not isinstance(profile, dict):
                return False
            fs = profile.get("filesystem")
            scoped = fs.get(":workspace_roots") if isinstance(fs, dict) else None
            if isinstance(scoped, dict) and scoped.get(".") == "write":
                return True
            current = profile.get("extends")
        return False

    def apply_directories(self, scope, plan, harness_id):
        target = plan.target_file
        requested = next((p for c in plan.contributions for p in c.paths), None)
        if plan.config_state == "unsupported":
            return WorktreeAccessStatus(
                harness_id,
                "unsupported",
                "not_applicable",
                str(target),
                requested,
                reason_code=plan.reason_code,
                reason="The selected Codex profile does not expose writable workspace roots.",
            )
        try:
            import tomlkit

            doc = self._load_doc(target)
            if doc is None:
                return WorktreeAccessStatus(
                    harness_id,
                    "failed",
                    "not_applicable",
                    str(target),
                    requested,
                    reason_code="CODEX_LEGACY_MALFORMED",
                    reason="Codex configuration is not readable.",
                )
            identity = DirectoryLedgerIdentity.from_scope(scope, harness_id)
            prior = read_directory_sidecar(identity)
            if prior is not None and prior.directory_ledger.get("native_key") != plan.native_key:
                old_plan = plan_directory_cleanup(self, scope, harness_id)
                old_status = apply_directory_cleanup(self, old_plan)
                if old_status.config_state == "failed":
                    return old_status
                prior = None
            if not plan.contributions and prior is None:
                return WorktreeAccessStatus(harness_id, "unmanaged", "not_applicable", str(target))
            ledger = (
                dict(prior.directory_ledger)
                if prior
                else {"native_key": plan.native_key, "contributions": {}, "entries": {}}
            )
            desired = [p for c in plan.contributions for p in c.paths]
            table = doc.get("sandbox_workspace_write")
            profile_name = plan.family.split(":", 1)[1] if plan.family.startswith("codex-profile:") else None
            roots_table = None
            if profile_name:
                permissions = doc.get("permissions")
                if not hasattr(permissions, "get"):
                    permissions = tomlkit.table()
                    doc["permissions"] = permissions
                table = permissions.get(profile_name)
                if table is None:
                    table = tomlkit.table()
                    permissions[profile_name] = table
                roots_table = table.get("workspace_roots")
                if not hasattr(roots_table, "get"):
                    roots_table = tomlkit.table()
                    table["workspace_roots"] = roots_table
            if table is None and not profile_name:
                table = tomlkit.table()
                doc["sandbox_workspace_write"] = table
            if not hasattr(table, "get"):
                return WorktreeAccessStatus(
                    harness_id,
                    "failed",
                    "not_applicable",
                    str(target),
                    requested,
                    reason_code="CODEX_LEGACY_MALFORMED",
                    reason="sandbox_workspace_write is not a table.",
                )
            if profile_name:
                raw_current = [
                    p for p, enabled in roots_table.items() if not isinstance(p, str) or not isinstance(enabled, bool)
                ]
                if raw_current:
                    raise ValueError("workspace_roots must map string paths to booleans")
                current = [p for p, enabled in roots_table.items() if enabled]
            else:
                raw_current = table.get("writable_roots", [])
                if not isinstance(raw_current, list) or any(not isinstance(p, str) or not p for p in raw_current):
                    raise ValueError("writable_roots must be a list of strings")
                current = list(raw_current)
            preexisting_counts = {p: current.count(p) for p in set(current)}
            old_entries = ledger.get("entries", {})
            for p in desired:
                if p not in current:
                    current.append(p)
            for p, info in old_entries.items():
                if p not in desired:
                    for _ in range(int((info or {}).get("owned_count", 0))):
                        if p in current:
                            current.remove(p)
            if profile_name:
                for path in desired:
                    roots_table[path] = True
                for old_path, info in old_entries.items():
                    if old_path not in desired and int((info or {}).get("owned_count", 0)):
                        roots_table.pop(old_path, None)
            else:
                table["writable_roots"] = current
            _atomic_replace(target, tomlkit.dumps(doc))
            ledger["contributions"] = {c.id: list(c.paths) for c in plan.contributions}
            ledger["identity"] = identity.to_dict()
            ledger["native_key"] = plan.native_key
            ledger["entries"] = {
                p: {
                    "owned_count": int((old_entries.get(p) or {}).get("owned_count", 0))
                    if p in old_entries
                    else (0 if preexisting_counts.get(p, 0) else 1),
                    "observed_preexisting_count": int(
                        (old_entries.get(p) or {}).get("observed_preexisting_count", preexisting_counts.get(p, 0))
                    ),
                    "last_verified_count": current.count(p),
                }
                for p in desired
            }
            if not ledger["contributions"] and not ledger["entries"]:
                delete_directory_sidecar(identity)
                return WorktreeAccessStatus(harness_id, "removed", "not_applicable", str(target))
            write_directory_sidecar(identity, target, ledger)
            missing = bool(requested and not Path(requested).exists())
            return WorktreeAccessStatus(
                harness_id,
                "configured",
                "restart_required",
                str(target),
                requested,
                missing,
                "CODEX_LEGACY_RESTART_REQUIRED",
                "Start a new session for Codex to load writable roots.",
            )
        except (OSError, ValueError, TypeError):
            return WorktreeAccessStatus(
                harness_id,
                "failed",
                "not_applicable",
                str(target),
                requested,
                reason_code="CODEX_LEGACY_MALFORMED",
                reason="Codex configuration is not a valid TOML document.",
            )

    def read_directories(self, scope, contributions, harness_id):
        plan = self.plan_directories(scope, contributions, harness_id)
        requested = next((p for c in contributions for p in c.paths), None)
        missing = bool(requested and not Path(requested).exists())
        if plan.config_state == "unsupported":
            return WorktreeAccessStatus(
                harness_id,
                "unsupported",
                "not_applicable",
                str(plan.target_file),
                requested,
                missing,
                plan.reason_code,
                "The selected Codex profile does not expose writable workspace roots.",
            )
        try:
            import tomlkit

            doc = self._load_doc(plan.target_file)
            if doc is None:
                raise ValueError
            if plan.family.startswith("codex-profile:"):
                name = plan.family.split(":", 1)[1]
                values = doc["permissions"][name]["workspace_roots"]
                if not isinstance(values, dict) or any(
                    not isinstance(k, str) or not isinstance(v, bool) for k, v in values.items()
                ):
                    raise ValueError
                configured = bool(requested and values.get(requested) is True)
            else:
                values = doc.get("sandbox_workspace_write", {}).get("writable_roots", [])
                if not isinstance(values, list) or any(not isinstance(p, str) or not p for p in values):
                    raise ValueError
                configured = bool(requested and requested in values)
            if requested and not configured:
                return WorktreeAccessStatus(
                    harness_id,
                    "failed",
                    "not_applicable",
                    str(plan.target_file),
                    requested,
                    missing,
                    "CODEX_DIRECTORY_MISSING",
                    "The requested directory grant is absent from native settings.",
                )
            ledger = read_directory_sidecar(DirectoryLedgerIdentity.from_scope(scope, harness_id))
            owned = bool(ledger and ledger.directory_ledger.get("entries", {}).get(requested, {}).get("owned_count", 0))
        except (OSError, ValueError, KeyError, TypeError, tomlkit.exceptions.ParseError):
            return WorktreeAccessStatus(
                harness_id,
                "failed",
                "not_applicable",
                str(plan.target_file),
                requested,
                missing,
                "CODEX_LEGACY_MALFORMED",
                "Codex configuration is not readable.",
            )
        return WorktreeAccessStatus(
            harness_id,
            "configured" if owned else "borrowed",
            "restart_required",
            str(plan.target_file),
            requested,
            missing,
            "CODEX_LEGACY_RESTART_REQUIRED",
            "Start a new session for Codex to load writable roots.",
        )

    def directory_cleanup_endpoint(self, scope, harness_id, native_key):
        if harness_id != "codex":
            raise ValueError("unsupported Codex harness")
        if native_key == "sandbox_workspace_write.writable_roots":
            target = (
                self.target_files(scope, harness_id)
                if isinstance(scope, GlobalScope)
                else Path(scope.path) / ".codex" / "config.toml"
            )
            return DirectoryEndpoint(target, native_key)
        parts = native_key.split(".")
        if len(parts) != 3 or parts[0] != "permissions" or parts[2] != "workspace_roots":
            raise ValueError("unsupported Codex directory key")
        if not parts[1] or not all(ch.isalnum() or ch in "_-" for ch in parts[1]):
            raise ValueError("invalid Codex profile key")
        target = (
            self.target_files(scope, harness_id)
            if isinstance(scope, GlobalScope)
            else Path(scope.path) / ".codex" / "config.toml"
        )
        return DirectoryEndpoint(target, native_key)

    def plan_owned_directory_removal(self, endpoint, entries):
        if not endpoint.target_file.exists():
            return None
        import tomlkit

        doc = self._load_doc(endpoint.target_file)
        if doc is None:
            raise ValueError("unreadable TOML")
        parts = endpoint.native_key.split(".")
        if endpoint.native_key == "sandbox_workspace_write.writable_roots":
            table = doc.get("sandbox_workspace_write")
            if not hasattr(table, "get"):
                raise ValueError("sandbox_workspace_write is not a table")
            current = table.get("writable_roots", [])
            if not isinstance(current, list) or any(not isinstance(p, str) or not p for p in current):
                raise ValueError("writable_roots must be a list of strings")
            kept = list(current)
            changed = False
            for path, info in entries.items():
                if not isinstance(path, str) or not isinstance(info, dict):
                    raise ValueError("invalid directory entry")
                count = info.get("owned_count")
                if isinstance(count, bool) or not isinstance(count, int) or count < 0:
                    raise ValueError("owned_count must be a non-negative integer")
                if count == 0:
                    continue
                for _ in range(count):
                    if path in kept:
                        kept.remove(path)
                        changed = True
            if not changed:
                return None
            table["writable_roots"] = kept
        else:
            permissions = doc.get("permissions")
            profile = permissions.get(parts[1]) if hasattr(permissions, "get") else None
            roots = profile.get("workspace_roots") if hasattr(profile, "get") else None
            if not isinstance(roots, dict) or any(
                not isinstance(p, str) or not isinstance(v, bool) for p, v in roots.items()
            ):
                raise ValueError("workspace_roots must map strings to booleans")
            changed = False
            for path, info in entries.items():
                if not isinstance(path, str) or not isinstance(info, dict):
                    raise ValueError("invalid directory entry")
                count = info.get("owned_count")
                if isinstance(count, bool) or not isinstance(count, int) or count < 0:
                    raise ValueError("owned_count must be a non-negative integer")
                if count == 0:
                    continue
                if path in roots:
                    roots.pop(path, None)
                    changed = True
            if not changed:
                return None
        return NativeDirectoryMutation(endpoint.target_file, endpoint.native_key, tomlkit.dumps(doc), "toml")

    def apply_owned_directory_removal(self, mutation):
        if mutation.content is not None:
            _atomic_replace(mutation.target_file, mutation.content)

    def cleanup_directories(self, scope, harness_id):
        return apply_directory_cleanup(self, plan_directory_cleanup(self, scope, harness_id))

    def apply(self, scope: Scope, write: NativeWrite, harness_id: str) -> bool:
        if write.format == "starlark":
            return self._apply_rules(scope, write, harness_id)
        return self._apply_toml(scope, write, harness_id)

    def _apply_rules(self, scope: Scope, write: NativeWrite, harness_id: str) -> bool:
        target = write.target_path
        _backup_once_per_session(target, scope, harness_id)
        if write.payload is None:
            # Deletion write — remove the hub rules file + its sidecar.
            if target.exists():
                try:
                    target.unlink()
                except OSError:
                    pass
            delete_sidecar(harness_id, scope, _RULES_SIDECAR_KIND)
            return True
        _atomic_replace(target, write.payload)
        write_sidecar(harness_id, scope, write.managed_keys, target, _RULES_SIDECAR_KIND)
        return True

    def _apply_toml(self, scope: Scope, write: NativeWrite, harness_id: str) -> bool:
        target = write.target_path
        _backup_once_per_session(target, scope, harness_id)

        doc = self._load_doc(target)
        if doc is None:
            return False

        import tomlkit

        # Strip prior managed keys
        prior = read_sidecar(harness_id, scope)
        if prior is not None and prior.managed_keys:
            for key in prior.managed_keys:
                _codex_strip_key(doc, key)

        payload = write.payload
        new_managed_keys: list[str] = []
        for k, v in payload.items():
            if k == "projects" and isinstance(v, dict):
                projects_tbl = doc.get("projects")
                if projects_tbl is None:
                    projects_tbl = tomlkit.table()
                    doc["projects"] = projects_tbl
                for proj_path, proj_data in v.items():
                    proj_tbl = projects_tbl.get(proj_path)
                    if proj_tbl is None:
                        proj_tbl = tomlkit.table()
                        projects_tbl[proj_path] = proj_tbl
                    for pk, pv in proj_data.items():
                        proj_tbl[pk] = pv
                        new_managed_keys.append(f"projects.{_codex_project_key(proj_path)}.{pk}")
            else:
                doc[k] = v
                new_managed_keys.append(k)

        _atomic_replace(target, tomlkit.dumps(doc))
        write_sidecar(harness_id, scope, new_managed_keys, target)
        return True

    def cleanup(self, scope: Scope, harness_id: str) -> bool:
        did = False

        # ── TOML sidecar: strip managed keys from config.toml ──
        sc = read_sidecar(harness_id, scope)
        if sc is not None:
            target = Path(sc.file)
            if not target.exists():
                delete_sidecar(harness_id, scope)
                did = True
            elif not _tomlkit_missing():
                import tomlkit

                doc = self._load_doc(target)
                if doc is not None:
                    for key in sc.managed_keys:
                        _codex_strip_key(doc, key)
                    _atomic_replace(target, tomlkit.dumps(doc))
                    delete_sidecar(harness_id, scope)
                    did = True
            # else: can't safely strip a TOML file we can't parse — leave the
            # sidecar in place; the next sync with tomlkit available finishes
            # the cleanup rather than crashing this one.

        # ── Rules sidecar: delete the hub-owned skill-hub.rules file ──
        rsc = read_sidecar(harness_id, scope, _RULES_SIDECAR_KIND)
        if rsc is not None:
            rules_file = Path(rsc.file)
            if rules_file.exists():
                try:
                    rules_file.unlink()
                except OSError:
                    pass
            delete_sidecar(harness_id, scope, _RULES_SIDECAR_KIND)
            did = True

        return did

    def discover_existing(
        self,
        scope: Scope,
        harness_id: str,
        project_path: Optional[Path] = None,
    ) -> NormalizedPermissions:
        # Reads only config.toml typed knobs / project trust. The user's
        # `default.rules` command rules are surfaced via `discover_candidates`
        # for the interactive import wizard (MOVE semantics), NOT auto-imported
        # during ordinary sync (D10/8.3).
        if _tomlkit_missing():
            return NormalizedPermissions()

        import tomlkit

        target = self.target_files(scope, harness_id)
        if not target.exists():
            return NormalizedPermissions()
        try:
            doc = tomlkit.parse(target.read_text())
        except Exception:
            return NormalizedPermissions()

        if isinstance(scope, GlobalScope):
            return NormalizedPermissions(
                approval_policy=doc.get("approval_policy"),
                sandbox_mode=doc.get("sandbox_mode"),
            )
        # Project scope
        projects = doc.get("projects") or {}
        proj_path = scope.path
        proj = projects.get(proj_path) if hasattr(projects, "get") else None
        if proj is None:
            return NormalizedPermissions()
        trust = proj.get("trust_level") if hasattr(proj, "get") else None
        return NormalizedPermissions(
            project_trust=(str(trust) == "trusted") if trust is not None else None,
        )

    def discover_candidates(
        self,
        scope: Scope,
        harness_id: str = "codex",
    ) -> list[dict]:
        """Discover importable command rules from the user's `default.rules`
        (and hub's own `skill-hub.rules`) for the interactive import wizard.

        Each candidate dict carries: `pattern` (registry-shaped, or None when
        un-importable), `kind`, `decision`, `source` ("default.rules" |
        "skill-hub.rules"), `harness`, `file`, `lineno`, `end_lineno`,
        `importable`, `reason`. A file that fails to parse is skipped with a
        warning (D4).
        """
        candidates: list[dict] = []
        for source, path in (
            ("default.rules", self.default_rules_file(scope)),
            ("skill-hub.rules", self.rules_file(scope)),
        ):
            if not path.exists():
                continue
            try:
                parsed = _parse_prefix_rules(path.read_text())
            except (SyntaxError, ValueError) as e:
                print(
                    f"warning: cannot parse {path}: {e} — skipping for import",
                    file=sys.stderr,
                )
                continue
            for pr in parsed:
                importable = pr["importable"]
                pattern = None
                kind = None
                if importable and pr["tokens"] is not None:
                    pattern = _prefix_rule_to_registry_pattern(pr["tokens"])
                    kind = _DECISION_TO_KIND.get(pr["decision"])
                    if kind is None:
                        importable = False
                candidates.append(
                    {
                        "pattern": pattern,
                        "kind": kind,
                        "decision": pr["decision"],
                        "source": source,
                        "harness": harness_id,
                        "file": str(path),
                        "lineno": pr["lineno"],
                        "end_lineno": pr["end_lineno"],
                        "importable": importable,
                        "reason": pr["reason"],
                    }
                )
        return candidates

    def excise_rule(self, file_path: Path, lineno: int, end_lineno: int) -> bool:
        """Surgically remove the `prefix_rule()` call spanning `lineno`..`end_lineno`
        (1-based, inclusive) from a `.rules` file, preserving everything else (D10).

        The file is backed up once per session before the first edit. Returns
        True on success, False if the file is gone.
        """
        if not file_path.exists():
            return False
        # Back up default.rules (user-owned) before the first surgical edit.
        scope_for_backup = GlobalScope()
        _backup_once_per_session(file_path, scope_for_backup, "codex")
        lines = file_path.read_text().splitlines(keepends=True)
        # Convert to 0-based slice; clamp defensively.
        start = max(0, lineno - 1)
        end = min(len(lines), end_lineno)
        if start >= end:
            return False
        del lines[start:end]
        _atomic_replace(file_path, "".join(lines))
        return True

    def excise_pattern(self, file_path: Path, pattern: str, kind: Optional[str] = None) -> bool:
        """Excise the `prefix_rule()` matching `pattern` (and optional `kind`)
        from a `.rules` file. Re-parses on each call so successive excises see
        fresh line spans. Returns True iff a matching rule was removed."""
        if not file_path.exists():
            return False
        try:
            parsed = _parse_prefix_rules(file_path.read_text())
        except (SyntaxError, ValueError):
            return False
        for pr in parsed:
            if not pr["tokens"]:
                continue
            if _prefix_rule_to_registry_pattern(pr["tokens"]) != pattern:
                continue
            if kind is not None and _DECISION_TO_KIND.get(pr["decision"]) != kind:
                continue
            return self.excise_rule(file_path, pr["lineno"], pr["end_lineno"])
        return False


def _codex_project_key(path: str) -> str:
    # Embed an absolute path inside a dotted JSONPath-ish key. We use a
    # bracketed-string-style segment to keep parsing simple in `_codex_strip_key`.
    return f'"{path}"'


def _codex_strip_key(doc, key: str) -> None:
    """Strip a single managed key path from a tomlkit doc.

    Supported forms:
        approval_policy
        sandbox_mode
        projects."<abs-path>".trust_level
    """
    # Special-case the projects."<path>".<field> form.
    if key.startswith("projects."):
        # Strip leading "projects." then peel off bracketed quoted path.
        rest = key[len("projects.") :]
        if not rest.startswith('"'):
            return
        end = rest.find('"', 1)
        if end == -1:
            return
        proj_path = rest[1:end]
        tail = rest[end + 1 :]
        if not tail.startswith(".") or not tail[1:]:
            return
        field_name = tail[1:]
        projects = doc.get("projects")
        if projects is None:
            return
        proj = projects.get(proj_path) if hasattr(projects, "get") else None
        if proj is None:
            return
        try:
            del proj[field_name]
        except KeyError:
            return
        # Optionally remove empty per-project table
        try:
            keys = list(proj.keys())
        except Exception:
            keys = []
        if not keys:
            try:
                del projects[proj_path]
            except KeyError:
                pass
        return

    # Plain top-level key
    try:
        del doc[key]
    except KeyError:
        return
