"""SDK-only native permission rule codecs.

Host policy, capability filtering, risk reporting, and file ownership remain
in the permission adapters. This module only translates bounded command rules
to and from Codex and OpenCode's native grammars.
"""

from __future__ import annotations

import ast
import json
import re
from types import MappingProxyType
from typing import Any, Mapping, Optional

from skill_hub.domain.harnesses.harness_adapter_api import (
    NativePermissionRuleObservation,
    PermissionCommandRule,
    PermissionNativeRuleCodec,
    PermissionPatternBlock,
    PermissionPatternCodec,
)

_CODEX_HEADER = "# Generated by Skill Hub — do not edit; managed via the hub registry."

_CLAUDE_PATTERN_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]*(?:\(.*\)|:[^()]*)?$")


class ClaudePermissionCodec:
    """Encode and validate Claude Code/Pi JSON permission pattern blocks."""

    @staticmethod
    def validation_error(pattern: object) -> Optional[str]:
        if not isinstance(pattern, str):
            return "empty pattern"
        value = pattern.strip()
        if not value:
            return "empty pattern"
        if value.count("(") != value.count(")"):
            return "unbalanced parentheses"
        if not _CLAUDE_PATTERN_RE.fullmatch(value):
            return "malformed pattern (expected Tool(arg) or Tool:arg)"
        return None

    def validate(self, pattern: object) -> bool:
        return self.validation_error(pattern) is None

    def encode(self, block: PermissionPatternBlock) -> Mapping[str, Any]:
        values = {
            "allow": block.allow,
            "deny": block.deny,
            "ask": block.ask,
            "additionalDirectories": block.additional_directories,
        }
        if any(not isinstance(value, str) for items in values.values() for value in items):
            raise TypeError("Claude permission block values must be strings")
        return MappingProxyType(
            {key: tuple(items) for key, items in values.items() if items}
        )

    def decode(self, native: object) -> PermissionPatternBlock:
        if not isinstance(native, Mapping):
            raise TypeError("Claude permission block must be an object")
        values: dict[str, tuple[str, ...]] = {}
        for key, field_name in (
            ("allow", "allow"),
            ("deny", "deny"),
            ("ask", "ask"),
            ("additionalDirectories", "additional_directories"),
        ):
            raw = native.get(key, ())
            if raw is None:
                raw = ()
            if not isinstance(raw, (list, tuple)):
                raise ValueError(f"Claude permission {key} must be an array")
            # Discovery intentionally stringifies native entries for parity with
            # the legacy host adapter, while preserving order and duplicates.
            values[field_name] = tuple(str(value) for value in raw)
        return PermissionPatternBlock(**values)


_CODEX_KIND_TO_DECISION = {"allow": "allow", "ask": "prompt", "deny": "forbidden"}
_CODEX_DECISION_TO_KIND = {value: key for key, value in _CODEX_KIND_TO_DECISION.items()}


def _codex_rule_line(rule: PermissionCommandRule) -> str:
    try:
        decision = _CODEX_KIND_TO_DECISION[rule.kind]
    except KeyError as exc:
        raise ValueError(f"unsupported permission kind: {rule.kind!r}") from exc
    if not rule.tokens or not all(isinstance(token, str) for token in rule.tokens):
        raise ValueError("Codex command rule tokens must be non-empty strings")
    tokens = "[" + ", ".join(json.dumps(token) for token in rule.tokens) + "]"
    justification = json.dumps(f"skill-hub: {rule.kind} {rule.source_pattern}")
    return (
        f"prefix_rule(pattern = {tokens}, decision = {json.dumps(decision)}, "
        f"justification = {justification})"
    )


class CodexPermissionCodec:
    """Encode and parse Codex's literal prefix_rule grammar."""

    @staticmethod
    def nonempty_literal(node: ast.AST) -> bool:
        try:
            return bool(ast.literal_eval(node))
        except Exception:
            return True

    def encode(self, rules: tuple[PermissionCommandRule, ...]) -> str:
        lines = [_CODEX_HEADER, ""]
        lines.extend(_codex_rule_line(rule) for rule in rules)
        return "\n".join(lines) + "\n"

    def decode(self, native: object) -> tuple[NativePermissionRuleObservation, ...]:
        if not isinstance(native, str):
            raise TypeError("Codex permission rules must be text")
        tree = ast.parse(native)
        observations: list[NativePermissionRuleObservation] = []
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            if not (isinstance(node.func, ast.Name) and node.func.id == "prefix_rule"):
                continue
            kwargs = {keyword.arg: keyword.value for keyword in node.keywords if keyword.arg}

            native_decision: Any = "allow"
            if "decision" in kwargs:
                try:
                    value = ast.literal_eval(kwargs["decision"])
                except Exception:
                    value = None
                native_decision = value

            justification = None
            if "justification" in kwargs:
                try:
                    justification = ast.literal_eval(kwargs["justification"])
                except Exception:
                    pass
            has_match = any(
                key in kwargs and self.nonempty_literal(kwargs[key])
                for key in ("match", "not_match")
            )
            pattern_node = kwargs.get("pattern")
            try:
                pattern_value = (
                    ast.literal_eval(pattern_node) if pattern_node is not None else None
                )
            except Exception:
                pattern_value = None
            tokens: Optional[tuple[str, ...]] = None
            importable = True
            reason: Optional[str] = None
            if (
                isinstance(pattern_value, list)
                and pattern_value
                and all(isinstance(token, str) for token in pattern_value)
            ):
                tokens = tuple(pattern_value)
            else:
                importable = False
                reason = "pattern is not a flat list of string literals (union/multi-alternative)"
            if has_match:
                importable = False
                reason = "uses match/not_match argument constraints"
            if not isinstance(native_decision, str) or native_decision not in _CODEX_DECISION_TO_KIND:
                importable = False
                reason = reason or f"unsupported decision {native_decision!r}"

            observations.append(
                NativePermissionRuleObservation(
                    tokens=tokens,
                    native_decision=native_decision,
                    importable=importable,
                    reason=reason,
                    lineno=node.lineno,
                    end_lineno=getattr(node, "end_lineno", node.lineno),
                    justification=justification,
                    has_match=has_match,
                )
            )
        return tuple(observations)

    def render_rule(self, rule: PermissionCommandRule) -> str:
        return _codex_rule_line(rule)


_OPENCODE_KIND_TO_DECISION = {"allow": "allow", "ask": "ask", "deny": "deny"}


def _opencode_prefix(tokens: tuple[str, ...]) -> str:
    if not tokens or not all(isinstance(token, str) and token for token in tokens):
        raise ValueError("OpenCode command rule tokens must be non-empty strings")
    return " ".join(tokens) + " *"


def _opencode_sort_key(tokens: tuple[str, ...]) -> tuple[int, int, tuple[str, ...]]:
    return (len(tokens), len(" ".join(tokens)), tokens)


def _opencode_prefix_text(prefix: object) -> Optional[str]:
    if not isinstance(prefix, str):
        return None
    value = prefix.strip()
    if value.endswith(" *"):
        value = value[:-2].strip()
    elif value.endswith("*"):
        value = value[:-1].strip()
    if not value or value == "*":
        return None
    return value


def _opencode_tokens(prefix: object) -> Optional[tuple[str, ...]]:
    value = _opencode_prefix_text(prefix)
    return tuple(value.split()) if value is not None else None


class OpenCodePermissionCodec:
    """Encode/decode OpenCode's last-match-wins bash permission map."""

    @staticmethod
    def bash_prefix(tokens: tuple[str, ...]) -> str:
        return _opencode_prefix(tokens)

    @staticmethod
    def pattern_from_prefix(prefix: object) -> Optional[str]:
        value = _opencode_prefix_text(prefix)
        return None if value is None else f"Bash({value}:*)"

    @staticmethod
    def sort_key(tokens: tuple[str, ...]) -> tuple[int, int, tuple[str, ...]]:
        return _opencode_sort_key(tokens)

    def encode(self, rules: tuple[PermissionCommandRule, ...]) -> Mapping[str, str]:
        ordered = sorted(rules, key=lambda rule: _opencode_sort_key(rule.tokens))
        output: dict[str, str] = {}
        for rule in ordered:
            try:
                decision = _OPENCODE_KIND_TO_DECISION[rule.kind]
            except KeyError as exc:
                raise ValueError(f"unsupported permission kind: {rule.kind!r}") from exc
            output[_opencode_prefix(rule.tokens)] = decision
        return MappingProxyType(output)

    def decode(self, native: object) -> tuple[NativePermissionRuleObservation, ...]:
        if not isinstance(native, Mapping):
            raise TypeError("OpenCode bash permissions must be an object")
        observations: list[NativePermissionRuleObservation] = []
        for prefix, decision in native.items():
            prefix = str(prefix)
            tokens = _opencode_tokens(prefix)
            native_decision = str(decision)
            importable = tokens is not None and native_decision in _OPENCODE_KIND_TO_DECISION.values()
            reason: Optional[str] = None
            if tokens is None:
                reason = "unbounded or malformed bash prefix"
            if native_decision not in _OPENCODE_KIND_TO_DECISION.values():
                reason = reason or "unsupported decision"
            observations.append(
                NativePermissionRuleObservation(
                    tokens=tokens,
                    native_decision=native_decision,
                    importable=importable,
                    reason=reason,
                    native_pattern=prefix,
                )
            )
        return tuple(observations)


_CODECS: Mapping[str, PermissionNativeRuleCodec] = {
    "codex": CodexPermissionCodec(),
    "opencode": OpenCodePermissionCodec(),
}

_PATTERN_CODECS: Mapping[str, PermissionPatternCodec] = {
    "claude": ClaudePermissionCodec(),
    "pi": ClaudePermissionCodec(),
}


def bundled_permission_codec(adapter_key: str) -> PermissionNativeRuleCodec:
    try:
        return _CODECS[adapter_key]
    except KeyError as exc:
        raise ValueError(f"unknown permission adapter key: {adapter_key!r}") from exc


def bundled_pattern_codec(adapter_key: str) -> PermissionPatternCodec:
    try:
        return _PATTERN_CODECS[adapter_key]
    except KeyError as exc:
        raise ValueError(f"unknown permission pattern adapter key: {adapter_key!r}") from exc


__all__ = [
    "CodexPermissionCodec",
    "OpenCodePermissionCodec",
    "ClaudePermissionCodec",
    "bundled_permission_codec",
    "bundled_pattern_codec",
]
