"""Focused contract tests for SDK-only native permission codecs."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from skill_hub.domain.harnesses.harness_adapter_api import (
    NativePermissionRuleObservation,
    PermissionCommandRule,
    PermissionPatternBlock,
)
from skill_hub.infrastructure.harnesses.harness_bundled_permissions import (
    ClaudePermissionCodec,
    CodexPermissionCodec,
    OpenCodePermissionCodec,
    bundled_pattern_codec,
    bundled_permission_codec,
)


def test_claude_pattern_codec_preserves_native_arrays_and_validates_patterns() -> None:
    codec = ClaudePermissionCodec()
    block = PermissionPatternBlock(
        allow=("Bash(npm:*)", "Bash(npm:*)"),
        deny=("Read(secrets/**)",),
        ask=("WebFetch(*)",),
        additional_directories=("/one", "/one"),
    )
    encoded = codec.encode(block)
    assert encoded == {
        "allow": ("Bash(npm:*)", "Bash(npm:*)"),
        "deny": ("Read(secrets/**)",),
        "ask": ("WebFetch(*)",),
        "additionalDirectories": ("/one", "/one"),
    }
    with pytest.raises(TypeError):
        encoded["allow"] += ("Write(*)",)  # type: ignore[index]
    assert codec.decode(encoded) == block
    assert codec.validate("Bash(npm:*)")
    assert not codec.validate("Bash(npm:*")
    assert not codec.validate("bad pattern")


def test_claude_pattern_codec_discovery_coerces_strings_and_refuses_bad_arrays() -> None:
    codec = bundled_pattern_codec("pi")
    assert codec.decode({"allow": [1, "Read(*)"]}).allow == ("1", "Read(*)")
    with pytest.raises(ValueError, match="must be an array"):
        codec.decode({"allow": "Bash(*)"})


def test_claude_codec_subprocess_is_sdk_only(tmp_path: Path) -> None:
    root = Path(__file__).resolve().parents[1]
    for name in (
        "skill_hub/domain/harnesses/harness_adapter_api.py",
        "skill_hub/infrastructure/harnesses/harness_bundled_permissions.py",
    ):
        (tmp_path / name).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(root / name, tmp_path / name)
    script = tmp_path / "sdk_pattern_check.py"
    script.write_text(
        "from skill_hub.domain.harnesses.harness_adapter_api import PermissionPatternBlock\n"
        "from skill_hub.infrastructure.harnesses.harness_bundled_permissions import bundled_pattern_codec\n"
        "codec = bundled_pattern_codec('claude')\n"
        "block = PermissionPatternBlock(allow=('Bash(npm:*)',), additional_directories=('/x',))\n"
        "assert codec.decode(codec.encode(block)) == block\n",
        encoding="utf-8",
    )
    completed = subprocess.run(
        [sys.executable, "-S", str(script)], cwd=tmp_path,
        env={**os.environ, "PYTHONPATH": str(tmp_path)},
        check=False, capture_output=True, text=True, timeout=10,
    )
    assert completed.returncode == 0, completed.stderr


def test_permission_records_are_immutable_and_freeze_tokens() -> None:
    tokens = ["git", "push"]
    rule = PermissionCommandRule(tokens, "allow", "Bash(git push:*)")
    tokens.append("--force")
    assert rule.tokens == ("git", "push")
    with pytest.raises(TypeError):
        rule.tokens[0] = "rm"  # type: ignore[index]

    observation = NativePermissionRuleObservation(["git"], "allow", True)
    assert observation.tokens == ("git",)
    with pytest.raises(TypeError):
        observation.tokens[0] = "rm"  # type: ignore[index]


def test_codex_render_is_byte_exact() -> None:
    codec = CodexPermissionCodec()
    rule = PermissionCommandRule(("git", "push"), "ask", "Bash(git push:*)")
    assert codec.encode((rule,)) == (
        "# Generated by Skill Hub — do not edit; managed via the hub registry.\n"
        "\n"
        'prefix_rule(pattern = ["git", "push"], decision = "prompt", '
        'justification = "skill-hub: ask Bash(git push:*)")\n'
    )


def test_codex_decode_reports_literal_refusals_and_source_spans() -> None:
    codec = CodexPermissionCodec()
    text = (
        'prefix_rule(pattern = ["npm"], decision = "allow")\n'
        "prefix_rule(\n"
        '    pattern = ["git", "push"], decision = "prompt",\n'
        ")\n"
        'prefix_rule(pattern = [["view", "list"]], decision = "allow")\n'
        'prefix_rule(pattern = ["gh"], decision = "allow", not_match = ["--force"])\n'
        'prefix_rule(pattern = ["rm"], decision = "unknown")\n'
    )
    observations = codec.decode(text)
    assert len(observations) == 5
    assert observations[0].tokens == ("npm",)
    assert observations[0].native_decision == "allow"
    assert observations[0].importable
    assert observations[1].tokens == ("git", "push")
    assert observations[1].end_lineno > observations[1].lineno  # multiline span
    assert not observations[2].importable
    assert "union" in (observations[2].reason or "")
    assert not observations[3].importable
    assert "match" in (observations[3].reason or "")
    assert not observations[4].importable
    assert observations[4].native_decision == "unknown"


def test_permission_codec_calls_do_not_share_outputs() -> None:
    codec = OpenCodePermissionCodec()
    rule = PermissionCommandRule(("npm",), "allow", "Bash(npm:*)")
    first = codec.encode((rule,))
    second = codec.encode((rule,))
    assert first == second == {"npm *": "allow"}
    with pytest.raises(TypeError):
        first["npm *"] = "deny"  # type: ignore[index]
    assert second == {"npm *": "allow"}


def test_opencode_orders_specific_rules_last_and_duplicate_wins() -> None:
    codec = OpenCodePermissionCodec()
    rules = (
        PermissionCommandRule(("git", "push"), "deny", "Bash(git push:*)"),
        PermissionCommandRule(("git",), "allow", "Bash(git:*)"),
        PermissionCommandRule(("git",), "ask", "Bash(git:*)"),
    )
    assert list(codec.encode(rules).items()) == [
        ("git *", "ask"),
        ("git push *", "deny"),
    ]


def test_opencode_decode_refuses_catchall_and_unknown_decisions() -> None:
    codec = OpenCodePermissionCodec()
    observations = codec.decode(
        {"git push *": "deny", "*": "allow", "npm *": "maybe"}
    )
    assert observations[0].tokens == ("git", "push")
    assert observations[0].importable
    assert observations[1].tokens is None
    assert not observations[1].importable
    assert observations[2].native_decision == "maybe"
    assert not observations[2].importable


def test_unknown_permission_codec_key_fails_closed() -> None:
    with pytest.raises(ValueError, match="unknown permission adapter key"):
        bundled_permission_codec("claude")


def test_codec_imports_from_sdk_only_directory(tmp_path: Path) -> None:
    root = Path(__file__).resolve().parents[1]
    for name in (
        "skill_hub/domain/harnesses/harness_adapter_api.py",
        "skill_hub/infrastructure/harnesses/harness_bundled_permissions.py",
    ):
        (tmp_path / name).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(root / name, tmp_path / name)
    env = os.environ.copy()
    env["PYTHONPATH"] = str(tmp_path)
    script = tmp_path / "sdk_check.py"
    script.write_text(
        "from skill_hub.domain.harnesses.harness_adapter_api import PermissionCommandRule\n"
        "from skill_hub.infrastructure.harnesses.harness_bundled_permissions import bundled_permission_codec\n"
        "result = bundled_permission_codec('opencode').encode(("
        "PermissionCommandRule(('git',), 'allow', 'Bash(git:*)'),))\n"
        "assert result == {'git *': 'allow'}\n",
        encoding="utf-8",
    )
    completed = subprocess.run(
        [sys.executable, "-S", str(script)],
        cwd=tmp_path,
        env=env,
        check=False,
        capture_output=True,
        text=True,
        timeout=10,
    )
    assert completed.returncode == 0, completed.stderr


@pytest.mark.parametrize("constraint", ["match=[]", "match=()", "not_match=[]", "match=False"])
def test_codex_empty_constraint_keeps_importable_rule_and_literal_metadata(constraint):
    """TA-1-f47f: pinned against the public `CodexPermissionCodec.decode`
    (the observation type already exposes these fields publicly), not the
    private key-renaming `_parse_prefix_rules` wrapper."""
    observed = CodexPermissionCodec().decode(
        'prefix_rule(pattern=["npm"], justification={"note": ["keep", (1, 2)]}, ' + constraint + ')'
    )[0]
    assert observed.importable is True
    assert observed.has_match is False
    # The public codec freezes nested structures (mappingproxy/tuple) so the
    # observation stays hashable-safe; the literal values still round-trip.
    assert dict(observed.justification) == {"note": ("keep", (1, 2))}
    assert isinstance(observed.justification["note"], tuple)
    assert isinstance(observed.justification["note"][1], tuple)


def test_codex_unknown_decision_retains_value_and_reason():
    """TA-1-f47f: pinned against the public codec decode; see the note above."""
    observation = CodexPermissionCodec().decode('prefix_rule(pattern=["git"], decision=123)')[0]
    assert not observation.importable
    assert observation.native_decision == 123
    assert observation.reason == "unsupported decision 123"


def test_opencode_import_preserves_native_spacing(tmp_path):
    import json

    from skill_hub.domain.permissions.permissions import ProjectScope
    from skill_hub.infrastructure.permissions.permission_adapter_opencode import OpenCodePermissionAdapter

    config = tmp_path / "opencode.json"
    config.write_text(json.dumps({"permission": {"bash": {"git  push *": "ask"}}}), encoding="utf-8")
    imported = OpenCodePermissionAdapter().discover_existing(ProjectScope("fixture", str(tmp_path)), "opencode")
    assert [rule.pattern for rule in imported.ask] == ["Bash(git  push:*)"]


def test_permission_observation_keeps_literal_metadata_immutable():
    observation = CodexPermissionCodec().decode(
        'prefix_rule(pattern=["git"], justification={"notes": ["keep"]})'
    )[0]
    with pytest.raises(TypeError):
        observation.justification["notes"] = []
    assert observation.justification["notes"] == ("keep",)
